"use client";

import { ArrowRight, Building2, CalendarClock, CheckCircle2, FileCheck2, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { ProjectRecord, WorkstreamRecord, WorkflowTemplateRecord } from "@/lib/domain-models";
import { WorkstreamGraphGantt, STATE_COLOR_MAP } from "./WorkstreamGraphGantt";
import { WorkflowJourney, WorkflowMiniStepper } from "./WorkflowJourney";

function formatDate(value?: string) {
  if (!value) return "Not set";
  const date = new Date(`${value.length === 10 ? `${value}T12:00:00` : value}`);
  if (Number.isNaN(date.valueOf())) return value;
  return date.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

function WorkstreamSummary({ workstream, focused, onFocus, workflowTemplates, customerSafe }: { workstream: WorkstreamRecord; focused: boolean; onFocus: () => void; workflowTemplates: WorkflowTemplateRecord[]; customerSafe: boolean }) {
  const state = STATE_COLOR_MAP[workstream.operationalState];
  return <button type="button" onClick={onFocus} className={`rounded-xl border p-4 text-left transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-teal-600 ${focused ? "border-teal-600 bg-teal-50 ring-2 ring-teal-200" : "border-slate-200 bg-white hover:border-teal-400 hover:bg-teal-50/40"}`}>
    <div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-mono text-[11px] font-black text-slate-500">{workstream.code}</p><p className="mt-1 text-sm font-black text-[#00284d]">{workstream.title}</p></div><span className={`rounded-full border px-2 py-1 text-[10px] font-black uppercase ${state.badgeBg} ${state.badgeText}`}>{state.shortLabel}</span></div>
    <div className="mt-3 grid gap-2 text-xs text-slate-600 sm:grid-cols-2"><span><strong>Stage:</strong> {workstream.currentStageName}</span><span><strong>Lead:</strong> {workstream.regulatoryLead.orgCode}</span><span><strong>Forecast:</strong> {formatDate(workstream.forecastTargetDate)}</span><span><strong>Variance:</strong> {workstream.scheduleVarianceDays > 0 ? `+${workstream.scheduleVarianceDays}d` : "On schedule"}</span></div>
    <p className="mt-3 border-t border-slate-100 pt-3 text-xs font-semibold text-slate-700">{workstream.currentActionSummary}</p>
    <WorkflowMiniStepper source={workstream} templates={workflowTemplates} customerSafe={customerSafe} />
  </button>;
}

export function ProjectOverviewPage({ project, customerSafe = false, workflowTemplates = [], focusedWorkstreamId, onFocusWorkstream, onOpenSchedule }: { project: ProjectRecord; customerSafe?: boolean; workflowTemplates?: WorkflowTemplateRecord[]; focusedWorkstreamId?: string | null; onFocusWorkstream: (workstreamId: string | null) => void; onOpenSchedule: () => void }) {
  const focused = project.workstreams.find(
    (workstream) =>
      workstream.id === focusedWorkstreamId ||
      workstream.code === focusedWorkstreamId ||
      workstream.code.toLowerCase() === focusedWorkstreamId?.toLowerCase()
  );
  const completeCount = project.workstreams.filter((workstream) => workstream.operationalState === "complete").length;
  const blockedCount = project.workstreams.filter((workstream) => workstream.operationalState === "blocked" || workstream.ragHealth === "red").length;
  const attentionCount = project.workstreams.filter((workstream) => workstream.ragHealth === "yellow").length;
  const onTrackCount = project.workstreams.length - blockedCount - attentionCount;
  const attentionWorkstream = project.workstreams.find((workstream) => workstream.operationalState === "blocked" || workstream.ragHealth === "red" || workstream.operationalState === "waiting_government" || workstream.operationalState === "waiting_applicant" || workstream.operationalState === "waiting_external") ?? project.workstreams.find((workstream) => workstream.ragHealth === "yellow");
  const activeWorkstream = project.workstreams.find((workstream) => workstream.operationalState === "running") ?? project.workstreams.find((workstream) => workstream.operationalState === "waiting_government" || workstream.operationalState === "waiting_applicant" || workstream.operationalState === "waiting_external") ?? project.workstreams.find((workstream) => workstream.operationalState !== "complete");
  const nextWorkstream = [...project.workstreams].filter((workstream) => workstream.operationalState !== "complete").sort((left, right) => left.forecastTargetDate.localeCompare(right.forecastTargetDate))[0];

  return <div className="space-y-6">
    <section className="rounded-2xl border border-teal-300 bg-white p-6 shadow-md sm:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-teal-800">{customerSafe ? "Customer project page" : "Authoritative project page"}</p><h1 className="mt-2 text-3xl font-black tracking-tight text-[#00284d] sm:text-4xl">{project.name}</h1><p className="mt-2 text-sm font-semibold text-slate-600">{project.code} · {project.locationDescription}</p></div><Badge className="border-amber-300 bg-amber-50 px-3 py-1.5 text-xs font-black uppercase text-amber-900">{project.overallRagHealth === "red" ? "At risk" : project.overallRagHealth === "yellow" ? "Attention" : "On track"}</Badge></div><div className="mt-7 grid gap-4 border-t border-slate-100 pt-5 sm:grid-cols-2 lg:grid-cols-5"><div><p className="text-[11px] font-black uppercase text-slate-500">Baseline launch</p><p className="mt-1 text-sm font-black text-[#00284d]">{formatDate(project.baselineLaunchDate)}</p></div><div><p className="text-[11px] font-black uppercase text-slate-500">Current forecast</p><p className="mt-1 text-sm font-black text-[#00284d]">{formatDate(project.currentForecastLaunchDate)}</p></div><div><p className="text-[11px] font-black uppercase text-slate-500">Variance</p><p className="mt-1 text-sm font-black text-rose-700">+{project.scheduleVarianceDays} days</p></div><div><p className="text-[11px] font-black uppercase text-slate-500">Workstreams</p><p className="mt-1 text-sm font-black text-[#00284d]">{completeCount}/{project.workstreams.length} complete</p></div><div><p className="text-[11px] font-black uppercase text-slate-500">Location</p><p className="mt-1 text-sm font-black text-[#00284d]">{project.parish}, Louisiana</p></div></div></section>
    <div className="grid gap-4 lg:grid-cols-3"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base font-black text-[#00284d]"><Building2 className="size-4 text-teal-700" /> Project ownership</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><div><p className="text-[11px] font-black uppercase text-slate-500">Applicant</p><p className="mt-1 font-bold text-slate-800">{project.applicantOrgCode}</p></div><div><p className="text-[11px] font-black uppercase text-slate-500">State lead</p><p className="mt-1 font-bold text-slate-800">{project.leadStateAgencyCode}</p><p className="text-xs text-slate-500">{project.stateProjectManagerName}</p></div><div><p className="text-[11px] font-black uppercase text-slate-500">Customer program manager</p><p className="mt-1 font-bold text-slate-800">{project.customerProgramManagerName}</p></div></CardContent></Card><Card><CardHeader><CardTitle className="text-base font-black text-[#00284d]">Delivery health</CardTitle></CardHeader><CardContent className="grid grid-cols-3 gap-2 text-center"><div className="rounded-lg border border-red-200 bg-red-50 p-3"><p className="text-[10px] font-black uppercase text-red-800">At risk</p><p className="mt-1 text-2xl font-black text-red-950">{blockedCount}</p></div><div className="rounded-lg border border-amber-200 bg-amber-50 p-3"><p className="text-[10px] font-black uppercase text-amber-800">Attention</p><p className="mt-1 text-2xl font-black text-amber-950">{attentionCount}</p></div><div className="rounded-lg border border-emerald-200 bg-emerald-50 p-3"><p className="text-[10px] font-black uppercase text-emerald-800">On track</p><p className="mt-1 text-2xl font-black text-emerald-950">{onTrackCount}</p></div></CardContent></Card><Card><CardHeader><CardTitle className="text-base font-black text-[#00284d]">Project records</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-slate-700"><p><FileCheck2 className="mr-2 inline size-4 text-teal-700" /><strong>{project.documents.length}</strong> document packages</p><p><CheckCircle2 className="mr-2 inline size-4 text-teal-700" /><strong>{project.commitments.length}</strong> commitments</p><p><CalendarClock className="mr-2 inline size-4 text-teal-700" /><strong>{project.decisions.length}</strong> decisions</p><p><Users className="mr-2 inline size-4 text-teal-700" /><strong>{project.participants?.length ?? 0}</strong> participants</p></CardContent></Card></div>
    <section aria-label="Project right now" className="rounded-2xl border border-slate-200 bg-slate-50 p-5 sm:p-6"><div className="mb-4"><p className="text-xs font-black uppercase tracking-[0.18em] text-teal-800">Project right now</p><h2 className="mt-1 text-xl font-black text-[#00284d]">What happened, what is happening, and what comes next</h2></div><div className="grid gap-3 md:grid-cols-3"><div className="rounded-xl border border-rose-200 bg-white p-4"><p className="text-[11px] font-black uppercase text-rose-800">Needs attention</p>{attentionWorkstream ? <><p className="mt-2 text-sm font-black text-[#00284d]">{attentionWorkstream.title}</p><p className="mt-1 text-xs text-slate-600">{attentionWorkstream.waitingReason ?? attentionWorkstream.currentActionSummary}</p></> : <p className="mt-2 text-sm font-semibold text-slate-600">Nothing is blocked.</p>}</div><div className="rounded-xl border border-teal-200 bg-white p-4"><p className="text-[11px] font-black uppercase text-teal-800">Happening now</p>{activeWorkstream ? <><p className="mt-2 text-sm font-black text-[#00284d]">{activeWorkstream.title}</p><p className="mt-1 text-xs text-slate-600">{activeWorkstream.currentActionSummary}</p></> : <p className="mt-2 text-sm font-semibold text-slate-600">All workstreams are complete.</p>}</div><div className="rounded-xl border border-sky-200 bg-white p-4"><p className="text-[11px] font-black uppercase text-sky-800">Next milestone</p>{nextWorkstream ? <><p className="mt-2 text-sm font-black text-[#00284d]">{nextWorkstream.title}</p><p className="mt-1 text-xs text-slate-600">{nextWorkstream.nextExpectedEvent} · {formatDate(nextWorkstream.forecastTargetDate)}</p></> : <p className="mt-2 text-sm font-semibold text-slate-600">Project complete.</p>}</div></div></section>
    <section><div className="mb-3 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-teal-800">Project execution detail</p><h2 className="mt-1 text-2xl font-black text-[#00284d]">Workstreams and current state</h2><p className="mt-1 text-sm text-slate-600">Each row shows the completed steps, the current step, and the next handoff.</p></div><Button type="button" variant="outline" onClick={onOpenSchedule} className="text-xs font-bold">Open full schedule <ArrowRight className="size-3.5" /></Button></div><div className="grid gap-3 md:grid-cols-2">{project.workstreams.map((workstream) => <WorkstreamSummary key={workstream.id} workstream={workstream} workflowTemplates={workflowTemplates} customerSafe={customerSafe} focused={workstream.id === focusedWorkstreamId || workstream.code === focusedWorkstreamId || workstream.code.toLowerCase() === focusedWorkstreamId?.toLowerCase()} onFocus={() => onFocusWorkstream(workstream.id)} />)}</div></section>
    {focused && <Card className="border-teal-300 bg-teal-50/40"><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-teal-800">Selected from DAG / Gantt</p><CardTitle className="mt-1 text-xl font-black text-[#00284d]">{focused.title}</CardTitle><p className="mt-1 text-sm text-slate-600">{focused.code} · {focused.currentStageName}</p></div><Button type="button" variant="outline" onClick={() => onFocusWorkstream(null)} className="text-xs font-bold">Clear focus</Button></div></CardHeader><CardContent className="space-y-4"><div className="grid gap-4 text-sm md:grid-cols-2 lg:grid-cols-4"><div><p className="text-[11px] font-black uppercase text-slate-500">Current state</p><p className="mt-1 font-black text-[#00284d]">{focused.operationalStateLabel}</p></div><div><p className="text-[11px] font-black uppercase text-slate-500">Owner</p><p className="mt-1 font-bold text-slate-800">{focused.regulatoryLead.assignedReviewerName}</p><p className="text-xs text-slate-500">{focused.regulatoryLead.orgName}</p></div><div><p className="text-[11px] font-black uppercase text-slate-500">Next expected event</p><p className="mt-1 font-bold text-slate-800">{focused.nextExpectedEvent}</p></div><div><p className="text-[11px] font-black uppercase text-slate-500">Customer action</p><p className="mt-1 font-bold text-slate-800">{focused.customerActionRequired}</p></div></div><WorkflowJourney source={focused} templates={workflowTemplates} customerSafe={customerSafe} /></CardContent></Card>}
    <Card><CardHeader><CardTitle className="flex items-center gap-2 text-lg font-black text-[#00284d]"><CalendarClock className="size-5 text-teal-700" /> Project timeline and dependencies</CardTitle><p className="text-sm text-slate-600">Historical baseline, current state, and future forecast are shown together.</p></CardHeader><CardContent className="p-0 sm:p-2"><WorkstreamGraphGantt project={project} customerSafe={customerSafe} onSelectWorkstream={onFocusWorkstream} /></CardContent></Card>
  </div>;
}
