import type {
  AssignmentGroupRecord,
  AssignmentGroupMembershipRecord,
  CommitmentRecord,
  CoordinationRequestRecord,
  DecisionRecord,
  DocumentRecord,
  MeetingRecord,
  OrganizationRecord,
  PermitTypeRecord,
  ProjectRecord,
  RFIRecord,
  WorkflowTemplateRecord,
  WorkstreamRecord,
} from "./domain-models";

// ==========================================
// 1. ORGANIZATIONS REGISTRY (HIERARCHICAL)
// ==========================================

export const registeredOrganizations: OrganizationRecord[] = [
  {
    id: "org-spacex",
    code: "SPACEX",
    name: "Space Exploration Technologies Corp.",
    abbreviation: "SpaceX",
    jurisdictionLevel: "Applicant",
    websiteUrl: "https://www.spacex.com",
    projectLiaisonName: "Maya Chen",
    projectLiaisonEmail: "maya.chen@spacex.test",
    projectLiaisonPhone: "(310) 363-6000",
    executiveEscalationName: "Gwynne Shotwell",
    executiveEscalationEmail: "gwynne.shotwell@spacex.test",
    workingHours: "24/7 Operations",
    holidayCalendar: "Federal & Engineering Shifts",
    defaultSlaDays: 5,
    documentRetentionYears: 20,
    isActive: true,
  },
  {
    id: "org-state-po",
    code: "LA-PROJECTS",
    name: "Louisiana Governor's Office of Major Projects & Delivery",
    abbreviation: "Project Office",
    jurisdictionLevel: "State",
    websiteUrl: "https://gov.louisiana.gov/major-projects",
    generalContactEmail: "delivery@la.gov",
    projectLiaisonName: "Sarah Johnson",
    projectLiaisonEmail: "sarah.johnson@la.gov",
    projectLiaisonPhone: "(225) 342-7000",
    executiveEscalationName: "Secretary of Economic Development",
    executiveEscalationEmail: "sec.econ@la.gov",
    workingHours: "Mon-Fri 7:30 AM - 5:30 PM CST",
    holidayCalendar: "Louisiana State Legal Holidays",
    defaultSlaDays: 5,
    statutoryAuthority: "La. R.S. 51:936 — Megaproject Coordination Authority",
    geographicCoverage: "State of Louisiana",
    documentRetentionYears: 15,
    isActive: true,
  },
  {
    id: "org-dotd",
    code: "DOTD",
    name: "Louisiana Department of Transportation and Development",
    abbreviation: "DOTD",
    jurisdictionLevel: "State",
    websiteUrl: "http://www.dotd.la.gov",
    permitPortalUrl: "https://ladotd.public.prod.web/permits",
    projectLiaisonName: "Mark Fontenot, PE",
    projectLiaisonEmail: "mark.fontenot@dotd.la.gov",
    projectLiaisonPhone: "(337) 262-6100",
    executiveEscalationName: "DOTD Chief Engineer",
    executiveEscalationEmail: "chief.eng@dotd.la.gov",
    workingHours: "Mon-Fri 8:00 AM - 4:30 PM CST",
    holidayCalendar: "Louisiana State Legal Holidays",
    defaultSlaDays: 20,
    statutoryAuthority: "La. R.S. 48:221 — State Highway System Access & Structural Loads",
    geographicCoverage: "District 03 — Acadiana & Coastal Parishes",
    documentRetentionYears: 10,
    isActive: true,
  },
  {
    id: "org-ldeq",
    code: "LDEQ",
    name: "Louisiana Department of Environmental Quality",
    abbreviation: "LDEQ",
    jurisdictionLevel: "State",
    websiteUrl: "https://www.deq.louisiana.gov",
    permitPortalUrl: "https://edms.deq.louisiana.gov",
    projectLiaisonName: "Dr. Rachel Benoit",
    projectLiaisonEmail: "rachel.benoit@la.gov",
    projectLiaisonPhone: "(225) 219-3181",
    executiveEscalationName: "Assistant Secretary, Office of Environmental Services",
    executiveEscalationEmail: "asst.sec.oes@la.gov",
    workingHours: "Mon-Fri 8:00 AM - 4:30 PM CST",
    holidayCalendar: "Louisiana State Legal Holidays",
    defaultSlaDays: 30,
    statutoryAuthority: "Louisiana Environmental Quality Act (La. R.S. 30:2001 et seq.)",
    geographicCoverage: "Statewide & Coastal Basins",
    documentRetentionYears: 30,
    isActive: true,
  },
  {
    id: "org-cpra",
    code: "CPRA",
    name: "Coastal Protection and Restoration Authority",
    abbreviation: "CPRA",
    jurisdictionLevel: "State",
    websiteUrl: "https://coastal.la.gov",
    permitPortalUrl: "https://sonris-cpra.dnr.state.la.us",
    projectLiaisonName: "Jean-Paul Guidry",
    projectLiaisonEmail: "jp.guidry@cpra.la.gov",
    projectLiaisonPhone: "(225) 342-7308",
    executiveEscalationName: "CPRA Executive Director",
    executiveEscalationEmail: "exec.cpra@la.gov",
    workingHours: "Mon-Fri 8:00 AM - 4:30 PM CST",
    holidayCalendar: "Louisiana State Legal Holidays",
    defaultSlaDays: 25,
    statutoryAuthority: "State and Local Coastal Resources Management Act (La. R.S. 49:214.21 et seq.)",
    geographicCoverage: "Louisiana Coastal Zone & Barrier Islands",
    documentRetentionYears: 20,
    isActive: true,
  },
  {
    id: "org-usace",
    code: "USACE",
    name: "U.S. Army Corps of Engineers — New Orleans District",
    abbreviation: "USACE-MVN",
    jurisdictionLevel: "Federal",
    websiteUrl: "https://www.mvn.usace.army.mil",
    permitPortalUrl: "https://crms.usace.army.mil",
    projectLiaisonName: "Col. Thomas Miller / Martin Breaux",
    projectLiaisonEmail: "martin.breaux@usace.army.mil",
    projectLiaisonPhone: "(504) 862-2201",
    executiveEscalationName: "District Commander",
    executiveEscalationEmail: "district.commander@usace.army.mil",
    workingHours: "Mon-Fri 7:30 AM - 4:00 PM CST",
    holidayCalendar: "Federal Holidays",
    defaultSlaDays: 60,
    statutoryAuthority: "Section 404 Clean Water Act (33 U.S.C. § 1344); Section 10 Rivers and Harbors Act",
    geographicCoverage: "Mississippi Valley Division — New Orleans District",
    documentRetentionYears: 50,
    isActive: true,
  },
  {
    id: "org-osfm",
    code: "OSFM",
    name: "Louisiana Office of State Fire Marshal",
    abbreviation: "OSFM",
    jurisdictionLevel: "State",
    websiteUrl: "https://sfm.dps.louisiana.gov",
    projectLiaisonName: "Chief Dan Thibodeaux",
    projectLiaisonEmail: "dan.thibodeaux@dps.la.gov",
    projectLiaisonPhone: "(225) 925-4911",
    workingHours: "Mon-Fri 8:00 AM - 4:30 PM CST",
    holidayCalendar: "Louisiana State Legal Holidays",
    defaultSlaDays: 14,
    statutoryAuthority: "La. R.S. 40:1561 — Life Safety & Hazardous Materials Review",
    geographicCoverage: "Statewide",
    documentRetentionYears: 15,
    isActive: true,
  },
  {
    id: "org-parish",
    code: "VERMILION-PARISH",
    name: "Vermilion Parish Police Jury & Permitting Office",
    abbreviation: "Vermilion Parish",
    jurisdictionLevel: "Local / Parish",
    websiteUrl: "https://www.vermilionparishpolicejury.com",
    projectLiaisonName: "David LeBlanc",
    projectLiaisonEmail: "dleblanc@vermilionparish.org",
    projectLiaisonPhone: "(337) 898-4300",
    workingHours: "Mon-Fri 8:00 AM - 4:00 PM CST",
    holidayCalendar: "Parish Legal Holidays",
    defaultSlaDays: 15,
    statutoryAuthority: "Vermilion Parish Code of Ordinances — Coastal Development",
    geographicCoverage: "Vermilion Parish — Pecan Island District",
    documentRetentionYears: 10,
    isActive: true,
  },
];

// ==========================================
// 1.1 ASSIGNMENT GROUPS (MULTI-AGENCY ITSM QUEUES)
// ==========================================

export const assignmentGroupsData: AssignmentGroupRecord[] = [
  // 1. SpaceX Internal Queues
  {
    id: "grp-spacex-tech",
    orgCode: "SPACEX",
    organizationId: "org-spacex",
    name: "SpaceX - Internal Technical Queue",
    description: "Launch mount structural civil engineering, high-pressure deluge, and mechanical interface reviews",
    leadUserId: "user-alex-martin",
    leadUserName: "Alex Martin",
    active: true,
  },
  {
    id: "grp-spacex-reg",
    orgCode: "SPACEX",
    organizationId: "org-spacex",
    name: "SpaceX - Regulatory Affairs Queue",
    description: "Multi-agency permit applications, NEPA environmental disclosures, and statutory compliance management",
    leadUserId: "user-maya-chen",
    leadUserName: "Maya Chen",
    active: true,
  },

  // 2. Governor's Project Office (State Concierge)
  {
    id: "grp-state-po-triage",
    orgCode: "LA-PROJECTS",
    organizationId: "org-state-po",
    name: "Governor's Project Office - Executive Triage & Delivery",
    description: "State-level executive intake, cross-agency critical path unblocking, and Cabinet escalation coordination",
    leadUserId: "user-sarah-johnson",
    leadUserName: "Sarah Johnson",
    active: true,
  },
  {
    id: "grp-state-po-concierge",
    orgCode: "LA-PROJECTS",
    organizationId: "org-state-po",
    name: "Governor's Project Office - Interagency Concierge",
    description: "Dedicated state concierge facilitating interagency concurrence, timeline alignment, and agency meetings",
    leadUserId: "user-sarah-johnson",
    leadUserName: "Sarah Johnson",
    active: true,
  },

  // 3. DOTD (Transportation & Development)
  {
    id: "grp-dotd-heavyhaul",
    orgCode: "DOTD",
    organizationId: "org-dotd",
    name: "DOTD - Structures & Bridge Review",
    description: "LA-82 bridge structural load simulations, axle weight distribution ratings, and culvert reinforcement engineering",
    leadUserId: "user-sam-rivera",
    leadUserName: "Sam Rivera",
    active: true,
  },
  {
    id: "grp-dotd-access",
    orgCode: "DOTD",
    organizationId: "org-dotd",
    name: "DOTD - Highway Access & Heavy-Haul",
    description: "State highway oversize superload routing, turning radius clearances, and drive connection permits",
    leadUserId: "user-sam-rivera",
    leadUserName: "Sam Rivera",
    active: true,
  },

  // 4. LDEQ (Environmental Quality)
  {
    id: "grp-ldeq-water",
    orgCode: "LDEQ",
    organizationId: "org-ldeq",
    name: "LDEQ - Water Quality & Deluge Permitting",
    description: "LPDES industrial stormwater, acoustic water deluge runoff retention, and baseline canal monitoring",
    leadUserId: "user-jordan-lee",
    leadUserName: "Jordan Lee",
    active: true,
  },
  {
    id: "grp-ldeq-air",
    orgCode: "LDEQ",
    organizationId: "org-ldeq",
    name: "LDEQ - Air Quality & Environmental Review",
    description: "Title V minor air source modeling, flare stack emissions limits, and environmental impact assessments",
    leadUserId: "user-jordan-lee",
    leadUserName: "Jordan Lee",
    active: true,
  },

  // 5. CPRA (Coastal Protection & Restoration Authority)
  {
    id: "grp-cpra-cup",
    orgCode: "CPRA",
    organizationId: "org-cpra",
    name: "CPRA - Coastal Use & Hydrology Permitting",
    description: "Coastal Use Permits (CUP), coastal zone management consistency, and Chenier Plain wetland ecology",
    leadUserId: "user-jean-paul-guidry",
    leadUserName: "Jean-Paul Guidry",
    active: true,
  },
  {
    id: "grp-cpra-levee",
    orgCode: "CPRA",
    organizationId: "org-cpra",
    name: "CPRA - Drainage & Levee Concurrence",
    description: "Hydrologic surge modeling, flood protection levee buffer concurrence, and coastal restoration alignment",
    leadUserId: "user-jean-paul-guidry",
    leadUserName: "Jean-Paul Guidry",
    active: true,
  },

  // 6. OSFM (Office of State Fire Marshal)
  {
    id: "grp-osfm-lifesafety",
    orgCode: "OSFM",
    organizationId: "org-osfm",
    name: "OSFM - Life Safety & Plan Review",
    description: "Commercial building safety codes, explosive setback compliance, and emergency egress routing",
    leadUserId: "user-dan-thibodeaux",
    leadUserName: "Chief Dan Thibodeaux",
    active: true,
  },
  {
    id: "grp-osfm-hazmat",
    orgCode: "OSFM",
    organizationId: "org-osfm",
    name: "OSFM - Hazardous Materials & Cryogenic Safety",
    description: "Liquid methane (LCH4), liquid oxygen (LOX) bulk storage, and cryogenic propellant transfer safety",
    leadUserId: "user-dan-thibodeaux",
    leadUserName: "Chief Dan Thibodeaux",
    active: true,
  },

  // 7. LSP (Louisiana State Police)
  {
    id: "grp-lsp-hazmat",
    orgCode: "LSP",
    organizationId: "org-lsp",
    name: "LSP - Emergency Response & Route Clearance",
    description: "State Police cryogenic transport escort coordination, highway rolling roadblocks, and emergency access",
    leadUserId: "user-robert-landry",
    leadUserName: "Capt. Robert Landry",
    active: true,
  },

  // 8. Vermilion Parish (Parish Permitting & Police Jury)
  {
    id: "grp-vermilion-parish",
    orgCode: "VERMILION-PARISH",
    organizationId: "org-parish",
    name: "Vermilion Parish - Coastal Permitting & Police Jury",
    description: "Parish coastal development permits, public hearing notices, and Police Jury ordinance consistency",
    leadUserId: "user-riley-brooks",
    leadUserName: "Riley Brooks",
    active: true,
  },
  {
    id: "grp-vermilion-publicworks",
    orgCode: "VERMILION-PARISH",
    organizationId: "org-parish",
    name: "Vermilion Parish - Public Works & Drainage",
    description: "Parish drainage canal crossings, bridge weight restrictions, and local road maintenance agreements",
    leadUserId: "user-riley-brooks",
    leadUserName: "Riley Brooks",
    active: true,
  },
];

export const assignmentGroupMembershipsData: AssignmentGroupMembershipRecord[] = [
  // SpaceX
  { id: "mem-spx-1", assignmentGroupId: "grp-spacex-tech", userId: "user-alex-martin", role: "lead", userName: "Alex Martin", userEmail: "alex.martin@spacex.com" },
  { id: "mem-spx-2", assignmentGroupId: "grp-spacex-tech", userId: "user-aris-thorne", role: "member", userName: "Dr. Aris Thorne", userEmail: "aris.thorne@gulfcoast-engineering.example" },
  { id: "mem-spx-3", assignmentGroupId: "grp-spacex-reg", userId: "user-maya-chen", role: "lead", userName: "Maya Chen", userEmail: "maya.chen@spacex.com" },
  { id: "mem-spx-4", assignmentGroupId: "grp-spacex-reg", userId: "user-alex-martin", role: "backup", userName: "Alex Martin", userEmail: "alex.martin@spacex.com" },

  // Governor's Project Office
  { id: "mem-gpo-1", assignmentGroupId: "grp-state-po-triage", userId: "user-sarah-johnson", role: "lead", userName: "Sarah Johnson", userEmail: "sarah.johnson@la.gov" },
  { id: "mem-gpo-2", assignmentGroupId: "grp-state-po-triage", userId: "user-joe-skaggs", role: "backup", userName: "Joe Skaggs", userEmail: "joe.skaggs@la.gov" },
  { id: "mem-gpo-3", assignmentGroupId: "grp-state-po-concierge", userId: "user-sarah-johnson", role: "lead", userName: "Sarah Johnson", userEmail: "sarah.johnson@la.gov" },

  // DOTD
  { id: "mem-dotd-1", assignmentGroupId: "grp-dotd-heavyhaul", userId: "user-sam-rivera", role: "lead", userName: "Sam Rivera", userEmail: "sam.rivera@la.gov" },
  { id: "mem-dotd-2", assignmentGroupId: "grp-dotd-access", userId: "user-sam-rivera", role: "lead", userName: "Sam Rivera", userEmail: "sam.rivera@la.gov" },

  // LDEQ
  { id: "mem-ldeq-1", assignmentGroupId: "grp-ldeq-water", userId: "user-jordan-lee", role: "lead", userName: "Jordan Lee", userEmail: "jordan.lee@la.gov" },
  { id: "mem-ldeq-2", assignmentGroupId: "grp-ldeq-air", userId: "user-jordan-lee", role: "lead", userName: "Jordan Lee", userEmail: "jordan.lee@la.gov" },

  // CPRA
  { id: "mem-cpra-1", assignmentGroupId: "grp-cpra-cup", userId: "user-jean-paul-guidry", role: "lead", userName: "Jean-Paul Guidry", userEmail: "jp.guidry@cpra.la.gov" },
  { id: "mem-cpra-2", assignmentGroupId: "grp-cpra-levee", userId: "user-jean-paul-guidry", role: "lead", userName: "Jean-Paul Guidry", userEmail: "jp.guidry@cpra.la.gov" },

  // OSFM
  { id: "mem-osfm-1", assignmentGroupId: "grp-osfm-lifesafety", userId: "user-dan-thibodeaux", role: "lead", userName: "Chief Dan Thibodeaux", userEmail: "dan.thibodeaux@dps.la.gov" },
  { id: "mem-osfm-2", assignmentGroupId: "grp-osfm-hazmat", userId: "user-dan-thibodeaux", role: "lead", userName: "Chief Dan Thibodeaux", userEmail: "dan.thibodeaux@dps.la.gov" },

  // LSP
  { id: "mem-lsp-1", assignmentGroupId: "grp-lsp-hazmat", userId: "user-robert-landry", role: "lead", userName: "Capt. Robert Landry", userEmail: "robert.landry@dps.la.gov" },

  // Vermilion Parish
  { id: "mem-parish-1", assignmentGroupId: "grp-vermilion-parish", userId: "user-riley-brooks", role: "lead", userName: "Riley Brooks", userEmail: "riley.brooks@vermilionparish.org" },
  { id: "mem-parish-2", assignmentGroupId: "grp-vermilion-publicworks", userId: "user-riley-brooks", role: "lead", userName: "Riley Brooks", userEmail: "riley.brooks@vermilionparish.org" },
];

// ==========================================
// 2. PERMIT / AUTHORIZATION CATALOG & 180-DAY RESOURCES
// ==========================================

export const permitCatalog: PermitTypeRecord[] = [
  {
    id: "cat-usace-404",
    code: "USACE-404",
    name: "Section 404 Wetland Fill & Dredge Authorization",
    category: "permit",
    responsibleOrgId: "org-usace",
    responsibleOrgCode: "USACE",
    triggerExplanation: "Discharge of dredged or fill material into waters of the United States, including coastal wetlands.",
    statutoryCitation: "33 U.S.C. § 1344; 33 CFR Parts 320-332",
    officialFilingUrl: "https://www.mvn.usace.army.mil/Missions/Regulatory/Permits/",
    applicationFormUrl: "https://www.usace.army.mil/forms/ENG4345.pdf",
    expectedLeadTimeDays: 120,
    minimumStatutoryDays: 30,
    publicNoticeRequired: true,
    publicNoticeDays: 30,
    prerequisites: ["Jurisdictional Wetland Delineation", "Alternatives Analysis (404(b)(1))", "Mitigation Plan"],
    relatedPermitTypeIds: ["cat-ldeq-401", "cat-cpra-cup"],
    lastVerifiedAt: "2026-08-25",
    verificationStatus: "verified",
    filingMode: "EXTERNAL_PORTAL",
    agencyContactName: "Martin Breaux, Regulatory Project Manager",
    agencyContactEmail: "martin.breaux@usace.army.mil",
    agencyContactPhone: "(504) 862-2201",
    resources: [
      {
        id: "res-usace-1",
        permitTypeId: "cat-usace-404",
        resourceName: "Form ENG 4345 Application Package",
        resourceType: "form_pdf",
        url: "https://www.mvn.usace.army.mil/forms/eng4345_2026.pdf",
        versionTag: "v4.2",
        effectiveDate: "2026-01-01",
        verifiedAt: "2026-08-25",
        verifiedBy: "Sarah Johnson",
        instructions: "Submit electronic copy with geospatial polygon shapefiles.",
        isStale: false,
      },
    ],
  },
  {
    id: "cat-cpra-cup",
    code: "CPRA-CUP",
    name: "Coastal Use Permit (CUP)",
    category: "permit",
    responsibleOrgId: "org-cpra",
    responsibleOrgCode: "CPRA",
    triggerExplanation: "Activities within the Louisiana Coastal Zone having direct and significant impact on coastal waters.",
    statutoryCitation: "La. R.S. 49:214.21 et seq.; LAC 43:I.723",
    officialFilingUrl: "https://sonris-cpra.dnr.state.la.us",
    expectedLeadTimeDays: 60,
    minimumStatutoryDays: 25,
    publicNoticeRequired: true,
    publicNoticeDays: 25,
    prerequisites: ["Site Plan & Cross Sections", "Coastal Zone Boundary Verification", "Drainage Concurrence"],
    relatedPermitTypeIds: ["cat-usace-404"],
    lastVerifiedAt: "2026-08-20",
    verificationStatus: "verified",
    filingMode: "EXTERNAL_PORTAL",
    agencyContactName: "Jean-Paul Guidry, Coastal Use Permitting",
    agencyContactEmail: "jp.guidry@cpra.la.gov",
    agencyContactPhone: "(225) 342-7308",
    resources: [
      {
        id: "res-cpra-1",
        permitTypeId: "cat-cpra-cup",
        resourceName: "Joint Coastal Use Application Portal",
        resourceType: "portal_url",
        url: "https://sonris-cpra.dnr.state.la.us/cup-portal",
        versionTag: "v5.0",
        verifiedAt: "2026-08-20",
        verifiedBy: "Jean-Paul Guidry",
        isStale: false,
      },
    ],
  },
  {
    id: "cat-dotd-heavyhaul",
    code: "DOTD-HEAVYHAUL",
    name: "Superload Heavy-Haul & Bridge Crossing Permit",
    category: "road",
    responsibleOrgId: "org-dotd",
    responsibleOrgCode: "DOTD",
    triggerExplanation: "Movement of vehicles or equipment exceeding statutory axle limits and bridge rating capacities on LA-82.",
    statutoryCitation: "La. R.S. 32:387; EDSM No. IV.2.1.8",
    officialFilingUrl: "https://ladotd.public.prod.web/permits/heavy-haul",
    expectedLeadTimeDays: 45,
    minimumStatutoryDays: 0,
    publicNoticeRequired: false,
    publicNoticeDays: 0,
    prerequisites: ["Axle Weight Distribution Matrix", "Bridge Structural Load Analysis", "Turn Radius Simulation"],
    relatedPermitTypeIds: ["cat-cpra-cup"],
    filingMode: "EXTERNAL_PORTAL",
    agencyContactName: "Sam Rivera, District 03 Permit Desk",
    agencyContactEmail: "sam.rivera@la.gov",
    agencyContactPhone: "(337) 262-6100",
    lastVerifiedAt: "2026-08-15",
    verificationStatus: "verified",
  },
];

// ==========================================
// 3. WORKFLOW TEMPLATES (STRUCTURED & VERSIONED)
// ==========================================

export const workflowTemplatesData: WorkflowTemplateRecord[] = [
  {
    id: "wt-coastal-v4",
    permitTypeId: "cat-cpra-cup",
    name: "Coastal Use Permit Standard Review",
    description: "Standard state-mandated coastal use review workflow under State and Local Coastal Resources Management Act.",
    activeVersionNumber: 4,
    versions: [
      {
        id: "wv-coastal-v4",
        templateId: "wt-coastal-v4",
        versionNumber: 4,
        status: "published",
        effectiveDate: "2026-01-15",
        publishedAt: "2026-01-10",
        publishedByName: "CPRA Permitting Administrator",
        changeSummary: "Added concurrent drainage concurrence gate with DOTD.",
        stages: [
          {
            id: "stage-cup-1",
            workflowVersionId: "wv-coastal-v4",
            stageKey: "intake",
            name: "Intake & Completeness Review",
            customerVisibilityLabel: "Intake Review",
            sequenceOrder: 1,
            responsibleOrgId: "org-cpra",
            responsibleOrgCode: "CPRA",
            targetDurationDays: 10,
            minimumStatutoryDays: 0,
            requiredInputs: ["site_plans", "wetlands_delineation"],
            completionRequirements: ["completeness_checklist_passed"],
            permittedTransitions: ["technical_review", "rfi", "return_to_applicant"],
            canRunInParallel: false,
            isMilestoneGate: false,
          },
          {
            id: "stage-cup-2",
            workflowVersionId: "wv-coastal-v4",
            stageKey: "technical_review",
            name: "Hydrology & Ecological Technical Review",
            customerVisibilityLabel: "Technical Review",
            sequenceOrder: 2,
            responsibleOrgId: "org-cpra",
            responsibleOrgCode: "CPRA",
            targetDurationDays: 20,
            minimumStatutoryDays: 0,
            requiredInputs: ["drainage_model", "mitigation_plan"],
            completionRequirements: ["drainage_concurrence_received", "ecological_signoff"],
            permittedTransitions: ["public_notice", "rfi", "reject"],
            canRunInParallel: true, // Can run in parallel with DOTD drainage review!
            isMilestoneGate: false,
          },
          {
            id: "stage-cup-3",
            workflowVersionId: "wv-coastal-v4",
            stageKey: "public_notice",
            name: "Statutory 25-Day Public Notice Period",
            customerVisibilityLabel: "Public Comment Period",
            sequenceOrder: 3,
            responsibleOrgId: "org-cpra",
            responsibleOrgCode: "CPRA",
            targetDurationDays: 25,
            minimumStatutoryDays: 25,
            requiredInputs: ["public_notice_text"],
            completionRequirements: ["public_comment_closed", "comment_response_package"],
            permittedTransitions: ["final_review", "comment_extension"],
            canRunInParallel: false,
            isMilestoneGate: true,
          },
          {
            id: "stage-cup-4",
            workflowVersionId: "wv-coastal-v4",
            stageKey: "decision",
            name: "Final Coastal Use Authorization Determination",
            customerVisibilityLabel: "Authorization Determination",
            sequenceOrder: 4,
            responsibleOrgId: "org-cpra",
            responsibleOrgCode: "CPRA",
            targetDurationDays: 5,
            minimumStatutoryDays: 0,
            requiredInputs: ["final_order_doc"],
            completionRequirements: ["executive_director_signature"],
            permittedTransitions: ["issued", "denied"],
            canRunInParallel: false,
            isMilestoneGate: true,
          },
        ],
      },
    ],
  },
];

// ==========================================
// 4. FIRST-CLASS COMMITMENTS (WHO / ACTION / PROMISED BY / MEETING)
// ==========================================

export const commitmentsData: CommitmentRecord[] = [
  {
    id: "COM-001",
    workstreamId: "WS-LA82-HEAVYHAUL",
    workstreamTitle: "LA-82 Heavy-Haul Access & Bridge Reinforcement",
    committingOrgId: "org-cpra",
    committingOrgCode: "CPRA",
    madeByPersonName: "Jean-Paul Guidry (CPRA)",
    committedAction: "Return consolidated drainage concurrence comments on Culvert 14B model",
    originContext: "Aug 29 Interagency Executive Standup Meeting",
    committedDate: "2026-08-29",
    promisedDueDate: "2026-09-05",
    status: "on_track",
    impactIfMissed: "DOTD structural crossing permit and LDEQ stormwater approval slip 7 calendar days",
    isCriticalPathImpact: true,
  },
  {
    id: "COM-002",
    workstreamId: "WS-LA82-HEAVYHAUL",
    workstreamTitle: "LA-82 Heavy-Haul Access & Bridge Reinforcement",
    committingOrgId: "org-spacex",
    committingOrgCode: "SPACEX",
    madeByPersonName: "Dr. Aris Thorne (SpaceX Lead Structures Engineer)",
    committedAction: "Deliver revised axle load distribution drawing package Rev 9 with dual-trailer configuration",
    originContext: "Aug 28 DOTD Structures Working Session",
    committedDate: "2026-08-28",
    promisedDueDate: "2026-09-03",
    status: "on_track",
    impactIfMissed: "DOTD Bridge Bureau load rating certification delayed by 5 days",
    isCriticalPathImpact: true,
  },
  {
    id: "COM-003",
    workstreamId: "WS-WETLANDS-PAD-A",
    workstreamTitle: "Launch Pad A – Wetland & Coastal Authorization",
    committingOrgId: "org-usace",
    committingOrgCode: "USACE",
    madeByPersonName: "Martin Breaux (USACE New Orleans District)",
    committedAction: "Issue official Completeness Determination letter for Section 404 Joint Application",
    originContext: "Aug 24 Bi-Weekly Federal Coordination Conference",
    committedDate: "2026-08-24",
    promisedDueDate: "2026-09-02",
    status: "at_risk",
    impactIfMissed: "30-day federal public notice publication delayed; slips Site Preparation Phase II start",
    isCriticalPathImpact: true,
  },
  {
    id: "COM-004",
    workstreamId: "WS-WASTEWATER-DELUGE",
    workstreamTitle: "Industrial Wastewater & Launch Deluge Retention Basin",
    committingOrgId: "org-ldeq",
    committingOrgCode: "LDEQ",
    madeByPersonName: "Dr. Rachel Benoit (LDEQ)",
    committedAction: "Deliver draft LPDES discharge permit for technical review after public hearing closure",
    originContext: "Aug 20 Water Permits Engineering Briefing",
    committedDate: "2026-08-20",
    promisedDueDate: "2026-09-04",
    status: "on_track",
    impactIfMissed: "Deluge retention basin earthwork commissioning slips 10 days",
    isCriticalPathImpact: false,
  },
  {
    id: "COM-005",
    workstreamId: "WS-GAS-LNG-PIPELINE",
    workstreamTitle: "Natural Gas Supply & Cryogenic LNG Pipeline Interconnect",
    committingOrgId: "org-state-po",
    committingOrgCode: "LA-PROJECTS",
    madeByPersonName: "Sarah Johnson (State PM)",
    committedAction: "Convene pipeline authority and Vermilion Parish easement right-of-way alignment",
    originContext: "Aug 27 Infrastructure Taskforce Meeting",
    committedDate: "2026-08-27",
    promisedDueDate: "2026-09-08",
    status: "on_track",
    impactIfMissed: "Pipeline crossing permit intake slips by 12 days",
    isCriticalPathImpact: true,
  },
  {
    id: "COM-006",
    workstreamId: "WS-SUBSTATION-230KV",
    workstreamTitle: "230kV Dual-Feed High-Capacity Grid Interconnect",
    committingOrgId: "org-spacex",
    committingOrgCode: "SPACEX",
    madeByPersonName: "Elena Vance (SpaceX Power Lead)",
    committedAction: "Provide final transformer impedance test parameters to Entergy Louisiana",
    originContext: "Aug 26 High-Voltage Grid Coordination Call",
    committedDate: "2026-08-26",
    promisedDueDate: "2026-09-06",
    status: "on_track",
    impactIfMissed: "Entergy protective relay programming delayed by 4 business days",
    isCriticalPathImpact: false,
  },
];

// ==========================================
// 5. INTERAGENCY COORDINATION REQUESTS (CR-00xxx)
// ==========================================

export const coordinationRequestsData: CoordinationRequestRecord[] = [
  {
    id: "cr-00451",
    code: "CR-00451",
    workstreamId: "WS-LA82-HEAVYHAUL",
    workstreamTitle: "LA-82 Heavy-Haul Access & Bridge Reinforcement",
    requestingOrgId: "org-dotd",
    requestingOrgCode: "DOTD",
    targetOrgId: "org-cpra",
    targetOrgCode: "CPRA",
    requestingUserName: "Mark Fontenot, PE (DOTD District 03)",
    assignedToUserName: "Jean-Paul Guidry (CPRA Coastal Permits)",
    title: "Drainage Concurrence for LA-82 Superload Culvert Reinforcement",
    needDescription: "DOTD requires CPRA formal concurrence that reinforced concrete box culverts at Mile Marker 14B will not alter tidal wetland hydrology before heavy-haul permit release.",
    requestedDate: "2026-08-29",
    dueDate: "2026-09-04",
    attachedDocumentVersionIds: ["doc-v-drainage-v12"],
    blocksWorkstreamTitle: "DOTD Heavy-Haul Improvement Authorization",
    priority: "critical_path",
    status: "in_review",
    responseSummary: "CPRA Coastal Engineers reviewing hydrodynamic model run 4B.",
  },
  {
    id: "cr-00452",
    code: "CR-00452",
    workstreamId: "WS-WASTEWATER-DELUGE",
    workstreamTitle: "Industrial Wastewater & Launch Deluge Retention Basin",
    requestingOrgId: "org-ldeq",
    requestingOrgCode: "LDEQ",
    targetOrgId: "org-cpra",
    targetOrgCode: "CPRA",
    requestingUserName: "Dr. Rachel Benoit (LDEQ Water Permits)",
    assignedToUserName: "Ecological Assessment Team (CPRA)",
    title: "Estuarine Discharge Salinity & Thermal Gradient Concurrence",
    needDescription: "Verification of thermal dissipation modeling for treated launch deluge cooling water discharge into coastal marsh canals.",
    requestedDate: "2026-08-22",
    dueDate: "2026-09-05",
    attachedDocumentVersionIds: ["doc-v-deluge-v8"],
    blocksWorkstreamTitle: "LPDES Industrial Wastewater Final Permit",
    priority: "normal",
    status: "pending",
  },
  {
    id: "cr-00453",
    code: "CR-00453",
    workstreamId: "WS-PUBLIC-SAFETY-AIRSPACE",
    workstreamTitle: "Gulf Airspace & Maritime Safety Corridor",
    requestingOrgId: "org-state-po",
    requestingOrgCode: "LA-PROJECTS",
    targetOrgId: "org-parish",
    targetOrgCode: "VERMILION-PARISH",
    requestingUserName: "Sarah Johnson (State PM)",
    assignedToUserName: "David LeBlanc (Vermilion Parish Sheriff Liaison)",
    title: "Launch Corridor Road Closure Inter-Governmental Agreement",
    needDescription: "Parish police jury resolution approving temporary LA-82 rolling checkpoints during static fire and flight test operations.",
    requestedDate: "2026-08-25",
    dueDate: "2026-09-10",
    attachedDocumentVersionIds: [],
    blocksWorkstreamTitle: "Flight Corridor Public Safety Closure Plan",
    priority: "high",
    status: "in_review",
  },
];

// ==========================================
// 6. FORMAL RFIs & CONSOLIDATED CYCLES
// ==========================================

export const rfisData: RFIRecord[] = [
  {
    id: "rfi-001",
    code: "RFI-2026-0042",
    workstreamId: "WS-LA82-HEAVYHAUL",
    workstreamTitle: "LA-82 Heavy-Haul Access & Bridge Reinforcement",
    requestingOrgId: "org-dotd",
    requestingOrgCode: "DOTD",
    recipientOrgId: "org-spacex",
    recipientOrgCode: "SPACEX",
    title: "Bridge Load Analysis & Dual-Trailer Configuration Drawing",
    questionText: "Please provide updated engineering drawings showing axle spacing and load distribution for the dual 14-axle transporter crossing the Freshwater Bayou Bridge on LA-82.",
    technicalReason: "State Bridge Rating Engineer requires certified axle load calculations to ensure deck flexure limits are not exceeded during booster transit.",
    requiredDocumentTypes: ["Structural Engineering Drawing (PE Stamped)", "Axle Load Matrix"],
    issuedDate: "2026-08-29",
    responseDeadline: "2026-09-03",
    clockImpact: "clock_paused",
    scheduleImpactDays: 5,
    status: "issued",
    isConsolidatedCycle: true,
    leadReviewerApprovedAt: "2026-08-29T14:30:00Z",
  },
  {
    id: "rfi-002",
    code: "RFI-2026-0039",
    workstreamId: "WS-WETLANDS-PAD-A",
    workstreamTitle: "Launch Pad A – Wetland & Coastal Authorization",
    requestingOrgId: "org-usace",
    requestingOrgCode: "USACE",
    recipientOrgId: "org-spacex",
    recipientOrgCode: "SPACEX",
    title: "Wetland Delineation Polygon Clarification on Eastern Berm",
    questionText: "Provide updated GIS polygon coordinates clarifying the exact acreage of saline marsh fill within Area B2.",
    technicalReason: "USACE Regulatory Project Manager detected a 0.4-acre discrepancy between the narrative description and the CAD layer.",
    requiredDocumentTypes: ["GIS Shapefiles", "Revised Delineation Map"],
    issuedDate: "2026-08-24",
    responseDeadline: "2026-09-01",
    clockImpact: "clock_paused",
    scheduleImpactDays: 7,
    status: "submitted_by_applicant",
    isConsolidatedCycle: false,
    responses: [
      {
        id: "resp-001",
        rfiId: "rfi-001",
        submittedByName: "Maya Chen (SpaceX)",
        responseText: "Attached revised GIS shapefile package Rev 4.1 aligning narrative with CAD coordinates (exact 18.2 acres).",
        attachedDocumentVersionIds: ["doc-v-wetland-v4"],
        submittedAt: "2026-08-29T16:00:00Z",
        reviewedByName: "Martin Breaux (USACE)",
        reviewDecision: "accepted",
        reviewNotes: "Discrepancy resolved; verified coordinates.",
        reviewedAt: "2026-08-30T09:00:00Z",
      },
    ],
  },
];

// ==========================================
// 7. PROJECT DOCUMENT VAULT (IMMUTABLE REVISIONS)
// ==========================================

export const projectDocumentsData: DocumentRecord[] = [
  {
    id: "doc-drainage-study",
    projectId: "proj-spacex-pecan",
    workstreamId: "WS-LA82-HEAVYHAUL",
    workstreamTitle: "LA-82 Heavy-Haul Access & Bridge Reinforcement",
    title: "LA-82 Heavy-Haul Drainage & Hydrodynamic Study",
    category: "engineering_drawing",
    ownerOrgCode: "SPACEX",
    currentVersionNumber: 12,
    isConfidential: false,
    versions: [
      {
        id: "doc-v-drainage-v11",
        documentId: "doc-drainage-study",
        versionTag: "v11.0",
        fileName: "LA82_Drainage_Model_v11.pdf",
        fileSizeBytes: 48291000,
        mimeType: "application/pdf",
        storageUri: "vault/drainage/LA82_Drainage_Model_v11.pdf",
        sha256Hash: "8a4f9b8c2e1d0f5a7b6c3e9d8f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a",
        uploadedByName: "Dr. Aris Thorne (SpaceX)",
        changeSummary: "Baseline hydrodynamic 10-year storm surge run.",
        isMalwareClean: true,
        uploadedAt: "2026-08-10T10:00:00Z",
      },
      {
        id: "doc-v-drainage-v12",
        documentId: "doc-drainage-study",
        versionTag: "v12.0",
        fileName: "LA82_Drainage_Model_v12_Culvert14B.pdf",
        fileSizeBytes: 52140000,
        mimeType: "application/pdf",
        storageUri: "vault/drainage/LA82_Drainage_Model_v12_Culvert14B.pdf",
        sha256Hash: "1f2e3d4c5b6a7f8e9d0c1b2a3f4e5d6c7b8a9f0e1d2c3b4a5f6e7d8c9b0a1f2e",
        uploadedByName: "Dr. Aris Thorne (SpaceX)",
        changeSummary: "Updated box culvert dimensions and tidal exchange velocity for CPRA concurrence CR-00451.",
        isMalwareClean: true,
        uploadedAt: "2026-08-29T11:30:00Z",
      },
    ],
    agencyReviews: [
      {
        id: "rev-dotd-drainage",
        documentVersionId: "doc-v-drainage-v12",
        workstreamId: "WS-LA82-HEAVYHAUL",
        reviewingOrgCode: "DOTD",
        reviewStatus: "approved",
        reviewedByName: "Mark Fontenot, PE",
        decisionDate: "2026-08-29",
        reviewComments: "DOTD Hydraulics approves Revision 12. Transmitted to CPRA for coastal concurrence.",
      },
      {
        id: "rev-cpra-drainage",
        documentVersionId: "doc-v-drainage-v12",
        workstreamId: "WS-LA82-HEAVYHAUL",
        reviewingOrgCode: "CPRA",
        reviewStatus: "under_review",
        reviewedByName: "Jean-Paul Guidry",
        reviewComments: "Reviewing tidal exchange coefficients under CR-00451.",
      },
    ],
  },
  {
    id: "doc-bridge-load",
    projectId: "proj-spacex-pecan",
    workstreamId: "WS-LA82-HEAVYHAUL",
    workstreamTitle: "LA-82 Heavy-Haul Access & Bridge Reinforcement",
    title: "Freshwater Bayou Bridge Structural Load Rating & Axle Matrix",
    category: "engineering_drawing",
    ownerOrgCode: "SPACEX",
    currentVersionNumber: 3,
    isConfidential: false,
    versions: [
      {
        id: "doc-v-bridge-v3",
        documentId: "doc-bridge-load",
        versionTag: "v3.0",
        fileName: "Freshwater_Bayou_Bridge_Axle_Matrix_v3.pdf",
        fileSizeBytes: 34180000,
        mimeType: "application/pdf",
        storageUri: "vault/bridge/Freshwater_Bayou_Bridge_Axle_Matrix_v3.pdf",
        sha256Hash: "a1b2c3d4e5f60718293a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e",
        uploadedByName: "Dr. Aris Thorne (SpaceX)",
        changeSummary: "Dual 14-axle transporter deck stress distribution model certified by PE.",
        isMalwareClean: true,
        uploadedAt: "2026-08-28T14:00:00Z",
      },
    ],
    agencyReviews: [
      {
        id: "rev-dotd-bridge",
        documentVersionId: "doc-v-bridge-v3",
        workstreamId: "WS-LA82-HEAVYHAUL",
        reviewingOrgCode: "DOTD",
        reviewStatus: "approved",
        reviewedByName: "Mark Fontenot, PE",
        decisionDate: "2026-08-29",
        reviewComments: "Structural rating verified acceptable for 320-ton payload.",
      },
    ],
  },
  {
    id: "doc-route-traffic",
    projectId: "proj-spacex-pecan",
    workstreamId: "WS-LA82-HEAVYHAUL",
    workstreamTitle: "LA-82 Heavy-Haul Access & Bridge Reinforcement",
    title: "LA-82 Heavy Transport Traffic Management & Escort Protocol",
    category: "public_safety",
    ownerOrgCode: "SPACEX",
    currentVersionNumber: 1,
    isConfidential: false,
    versions: [
      {
        id: "doc-v-traffic-v1",
        documentId: "doc-route-traffic",
        versionTag: "v1.0",
        fileName: "LA82_Transport_Traffic_Plan_v1.0.pdf",
        fileSizeBytes: 18240000,
        mimeType: "application/pdf",
        storageUri: "vault/traffic/LA82_Transport_Traffic_Plan_v1.0.pdf",
        sha256Hash: "b2c3d4e5f6a708192a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f",
        uploadedByName: "Maya Chen (SpaceX)",
        changeSummary: "Initial state police rolling closure and escort coordination plan.",
        isMalwareClean: true,
        uploadedAt: "2026-08-25T09:30:00Z",
      },
    ],
    agencyReviews: [
      {
        id: "rev-lsp-traffic",
        documentVersionId: "doc-v-traffic-v1",
        workstreamId: "WS-LA82-HEAVYHAUL",
        reviewingOrgCode: "LSP",
        reviewStatus: "approved",
        reviewedByName: "Capt. Tyler Vance",
        decisionDate: "2026-08-27",
        reviewComments: "Troop I escort staffing schedule confirmed.",
      },
    ],
  },
  {
    id: "doc-wetland-package",
    projectId: "proj-spacex-pecan",
    workstreamId: "WS-WETLANDS-PAD-A",
    workstreamTitle: "Launch Pad A – Wetland & Coastal Authorization",
    title: "Launch Complex Wetland Delineation & Mitigation Package",
    category: "environmental_study",
    ownerOrgCode: "SPACEX",
    currentVersionNumber: 4,
    isConfidential: false,
    versions: [
      {
        id: "doc-v-wetland-v4",
        documentId: "doc-wetland-package",
        versionTag: "v4.1",
        fileName: "Pecan_Island_Wetland_Delineation_v4.1.pdf",
        fileSizeBytes: 64200000,
        mimeType: "application/pdf",
        storageUri: "vault/wetlands/Pecan_Island_Wetland_Delineation_v4.1.pdf",
        sha256Hash: "c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4",
        uploadedByName: "Maya Chen (SpaceX)",
        changeSummary: "Reconciled Area B2 boundary per RFI-2026-0039.",
        isMalwareClean: true,
        uploadedAt: "2026-08-29T15:45:00Z",
      },
    ],
    agencyReviews: [
      {
        id: "rev-usace-wetland",
        documentVersionId: "doc-v-wetland-v4",
        workstreamId: "WS-WETLANDS-PAD-A",
        reviewingOrgCode: "USACE",
        reviewStatus: "approved",
        reviewedByName: "Martin Breaux",
        decisionDate: "2026-08-30",
        reviewComments: "Delineation boundaries confirmed accurate.",
      },
      {
        id: "rev-ldeq-wetland",
        documentVersionId: "doc-v-wetland-v4",
        workstreamId: "WS-WETLANDS-PAD-A",
        reviewingOrgCode: "LDEQ",
        reviewStatus: "under_review",
        reviewedByName: "Dr. Rachel Benoit",
      },
    ],
  },
  {
    id: "doc-deluge-discharge",
    projectId: "proj-spacex-pecan",
    workstreamId: "WS-WASTEWATER-DELUGE",
    workstreamTitle: "Industrial Wastewater & Launch Deluge Retention Basin",
    title: "Industrial Deluge Water Containment & Retention Basin Report",
    category: "environmental_study",
    ownerOrgCode: "SPACEX",
    currentVersionNumber: 2,
    isConfidential: false,
    versions: [
      {
        id: "doc-v-deluge-v2",
        documentId: "doc-deluge-discharge",
        versionTag: "v2.0",
        fileName: "Deluge_Water_Quality_Retention_Model_v2.0.pdf",
        fileSizeBytes: 39500000,
        mimeType: "application/pdf",
        storageUri: "vault/deluge/Deluge_Water_Quality_Retention_Model_v2.0.pdf",
        sha256Hash: "d4e5f6a7b8c90123456789abcdef0123456789abcdef0123456789abcdef0123",
        uploadedByName: "Maya Chen (SpaceX)",
        changeSummary: "Post-static fire acoustic deluge water sampling and retention basin liner specs.",
        isMalwareClean: true,
        uploadedAt: "2026-08-20T11:00:00Z",
      },
    ],
    agencyReviews: [
      {
        id: "rev-ldeq-deluge",
        documentVersionId: "doc-v-deluge-v2",
        workstreamId: "WS-WASTEWATER-DELUGE",
        reviewingOrgCode: "LDEQ",
        reviewStatus: "under_review",
        reviewedByName: "Dr. Rachel Benoit",
        reviewComments: "Reviewing TDS and thermal dissipation model under LPDES draft conditions.",
      },
    ],
  },
  {
    id: "doc-pipeline-safety",
    projectId: "proj-spacex-pecan",
    workstreamId: "WS-GAS-LNG-PIPELINE",
    workstreamTitle: "Liquid Methane & Gas Utility Interconnection",
    title: "Natural Gas Utility Interconnection & Pipeline Safety Study",
    category: "engineering_drawing",
    ownerOrgCode: "SPACEX",
    currentVersionNumber: 1,
    isConfidential: false,
    versions: [
      {
        id: "doc-v-pipeline-v1",
        documentId: "doc-pipeline-safety",
        versionTag: "v1.0",
        fileName: "Methane_Pipeline_Alignment_Cathodic_v1.0.pdf",
        fileSizeBytes: 27800000,
        mimeType: "application/pdf",
        storageUri: "vault/pipeline/Methane_Pipeline_Alignment_Cathodic_v1.0.pdf",
        sha256Hash: "e5f6a7b8c9d0123456789abcdef0123456789abcdef0123456789abcdef01234",
        uploadedByName: "Dr. Aris Thorne (SpaceX)",
        changeSummary: "12-inch high-pressure methane pipeline route alignment and cathodic protection specs.",
        isMalwareClean: true,
        uploadedAt: "2026-08-18T14:15:00Z",
      },
    ],
    agencyReviews: [
      {
        id: "rev-denr-pipeline",
        documentVersionId: "doc-v-pipeline-v1",
        workstreamId: "WS-GAS-LNG-PIPELINE",
        reviewingOrgCode: "DENR",
        reviewStatus: "under_review",
        reviewedByName: "Brett Landry, PE",
        reviewComments: "Pipeline safety division reviewing valve spacing and marsh depth.",
      },
    ],
  },
  {
    id: "doc-substation-singleline",
    projectId: "proj-spacex-pecan",
    workstreamId: "WS-SUBSTATION-230KV",
    workstreamTitle: "230kV Grid Interconnection & Substation Expansion",
    title: "230kV Substation Interconnection Single-Line & Protection Diagrams",
    category: "engineering_drawing",
    ownerOrgCode: "SPACEX",
    currentVersionNumber: 2,
    isConfidential: false,
    versions: [
      {
        id: "doc-v-substation-v2",
        documentId: "doc-substation-singleline",
        versionTag: "v2.1",
        fileName: "230kV_Substation_SingleLine_Relay_v2.1.pdf",
        fileSizeBytes: 31200000,
        mimeType: "application/pdf",
        storageUri: "vault/substation/230kV_Substation_SingleLine_Relay_v2.1.pdf",
        sha256Hash: "f6a7b8c9d0e123456789abcdef0123456789abcdef0123456789abcdef012345",
        uploadedByName: "Maya Chen (SpaceX)",
        changeSummary: "Dual redundant 230kV transformer bus architecture aligning with Entergy Louisiana specs.",
        isMalwareClean: true,
        uploadedAt: "2026-08-22T16:00:00Z",
      },
    ],
    agencyReviews: [
      {
        id: "rev-lpsc-substation",
        documentVersionId: "doc-v-substation-v2",
        workstreamId: "WS-SUBSTATION-230KV",
        reviewingOrgCode: "LPSC",
        reviewStatus: "approved",
        reviewedByName: "Gregory Hayes, PE",
        decisionDate: "2026-08-28",
        reviewComments: "Interconnection agreement engineering review certified.",
      },
    ],
  },
  {
    id: "doc-flight-safety-plan",
    projectId: "proj-spacex-pecan",
    workstreamId: "WS-PUBLIC-SAFETY-AIRSPACE",
    workstreamTitle: "Gulf Airspace & Maritime Safety Corridor",
    title: "Launch Flight Safety Hazard Analysis & Offshore Exclusion Zone Plan",
    category: "public_safety",
    ownerOrgCode: "SPACEX",
    currentVersionNumber: 1,
    isConfidential: false,
    versions: [
      {
        id: "doc-v-flight-v1",
        documentId: "doc-flight-safety-plan",
        versionTag: "v1.0",
        fileName: "Launch_Flight_Safety_Corridor_Hazard_v1.0.pdf",
        fileSizeBytes: 44100000,
        mimeType: "application/pdf",
        storageUri: "vault/safety/Launch_Flight_Safety_Corridor_Hazard_v1.0.pdf",
        sha256Hash: "0718293a4b5cdef0123456789abcdef0123456789abcdef0123456789abcdef0",
        uploadedByName: "Maya Chen (SpaceX)",
        changeSummary: "FAA Part 450 trajectory modeling, debris dispersion footprint, and USCG NOTMAR notice window.",
        isMalwareClean: true,
        uploadedAt: "2026-08-15T08:00:00Z",
      },
    ],
    agencyReviews: [
      {
        id: "rev-lsp-flight",
        documentVersionId: "doc-v-flight-v1",
        workstreamId: "WS-PUBLIC-SAFETY-AIRSPACE",
        reviewingOrgCode: "LSP",
        reviewStatus: "approved",
        reviewedByName: "Capt. Tyler Vance",
        decisionDate: "2026-08-26",
        reviewComments: "Multi-agency emergency response annex approved.",
      },
      {
        id: "rev-parish-flight",
        documentVersionId: "doc-v-flight-v1",
        workstreamId: "WS-PUBLIC-SAFETY-AIRSPACE",
        reviewingOrgCode: "VERMILION-PARISH",
        reviewStatus: "under_review",
        reviewedByName: "David LeBlanc",
        reviewComments: "Police Jury reviewing rolling road closure resolution CR-00453.",
      },
    ],
  },
  {
    id: "doc-osfm-fire-suppression",
    projectId: "proj-spacex-pecan",
    workstreamId: "WS-HIGHBAY-OSFM",
    workstreamTitle: "Vertical Integration Facility High-Bay Structural & Fire Safety",
    title: "OSFM High-Bay Fire Suppression & Structural Code Review",
    category: "engineering_drawing",
    ownerOrgCode: "SPACEX",
    currentVersionNumber: 5,
    isConfidential: false,
    versions: [
      {
        id: "doc-v-osfm-v5",
        documentId: "doc-osfm-fire-suppression",
        versionTag: "v5.0",
        fileName: "OSFM_HighBay_Fire_Suppression_Rev5.pdf",
        fileSizeBytes: 58900000,
        mimeType: "application/pdf",
        storageUri: "vault/osfm/OSFM_HighBay_Fire_Suppression_Rev5.pdf",
        sha256Hash: "18293a4b5c6def0123456789abcdef0123456789abcdef0123456789abcdef01",
        uploadedByName: "Maya Chen (SpaceX)",
        changeSummary: "Foam-water deluge system hydraulic calculations and NFPA 13 compliance certification.",
        isMalwareClean: true,
        uploadedAt: "2026-08-12T13:00:00Z",
      },
    ],
    agencyReviews: [
      {
        id: "rev-osfm-building",
        documentVersionId: "doc-v-osfm-v5",
        workstreamId: "WS-HIGHBAY-OSFM",
        reviewingOrgCode: "OSFM",
        reviewStatus: "approved",
        reviewedByName: "Chief Inspector Dave Fontenot",
        decisionDate: "2026-08-15",
        reviewComments: "Final commercial building permit and life safety certificate issued.",
      },
    ],
  },
  {
    id: "doc-workforce-mou",
    projectId: "proj-spacex-pecan",
    workstreamId: "WS-WORKFORCE-CONSORTIUM",
    workstreamTitle: "Aerospace Workforce Training & Certification Facility",
    title: "Louisiana FastStart Aerospace Training Curriculum Agreement",
    category: "contract_agreement",
    ownerOrgCode: "LED",
    currentVersionNumber: 1,
    isConfidential: false,
    versions: [
      {
        id: "doc-v-workforce-v1",
        documentId: "doc-workforce-mou",
        versionTag: "v1.0",
        fileName: "Louisiana_FastStart_Aerospace_Curriculum_v1.0.pdf",
        fileSizeBytes: 14500000,
        mimeType: "application/pdf",
        storageUri: "vault/workforce/Louisiana_FastStart_Aerospace_Curriculum_v1.0.pdf",
        sha256Hash: "293a4b5c6d7def0123456789abcdef0123456789abcdef0123456789abcdef02",
        uploadedByName: "Paul Helton (LED FastStart)",
        changeSummary: "Curriculum specifications, cleanroom simulator requirements, and NDT technician training MOU.",
        isMalwareClean: true,
        uploadedAt: "2026-07-28T10:00:00Z",
      },
    ],
    agencyReviews: [
      {
        id: "rev-led-workforce",
        documentVersionId: "doc-v-workforce-v1",
        workstreamId: "WS-WORKFORCE-CONSORTIUM",
        reviewingOrgCode: "LED",
        reviewStatus: "approved",
        reviewedByName: "Paul Helton",
        decisionDate: "2026-08-01",
        reviewComments: "State economic development consortium agreement executed.",
      },
    ],
  },
  {
    id: "doc-substation-ph2-preapp",
    projectId: "proj-spacex-pecan",
    workstreamId: "WS-PREAPP-SUBSTATION-PH2",
    workstreamTitle: "Pre-Application: 230kV Substation Expansion Phase II",
    title: "Phase II Grid Expansion Feasibility & Environmental Screening",
    category: "environmental_study",
    ownerOrgCode: "SPACEX",
    currentVersionNumber: 1,
    isConfidential: false,
    versions: [
      {
        id: "doc-v-substationph2-v1",
        documentId: "doc-substation-ph2-preapp",
        versionTag: "v1.0",
        fileName: "Phase2_Substation_Feasibility_Screening_v1.0.pdf",
        fileSizeBytes: 21300000,
        mimeType: "application/pdf",
        storageUri: "vault/substation_ph2/Phase2_Substation_Feasibility_Screening_v1.0.pdf",
        sha256Hash: "3a4b5c6d7e8def0123456789abcdef0123456789abcdef0123456789abcdef03",
        uploadedByName: "Maya Chen (SpaceX)",
        changeSummary: "Initial preliminary load screening and wetland avoidance analysis for Phase II booster test stands.",
        isMalwareClean: true,
        uploadedAt: "2026-08-26T15:00:00Z",
      },
    ],
    agencyReviews: [
      {
        id: "rev-lpsc-ph2",
        documentVersionId: "doc-v-substationph2-v1",
        workstreamId: "WS-PREAPP-SUBSTATION-PH2",
        reviewingOrgCode: "LPSC",
        reviewStatus: "under_review",
        reviewedByName: "Gregory Hayes, PE",
        reviewComments: "Pre-application consultation underway.",
      },
    ],
  },
];

// ==========================================
// 8. INSTITUTIONAL DECISION LOGS (WITH STATUTORY CITATIONS)
// ==========================================

export const projectDecisionsData: DecisionRecord[] = [
  {
    id: "DEC-2026-001",
    projectId: "proj-spacex-pecan",
    decisionDate: "2026-08-15",
    title: "CPRA and USACE Concurrent Technical Review Authorization",
    decisionSummary: "Agreed that CPRA Coastal Use Technical Review will execute concurrently with USACE Section 404 Completeness Review rather than waiting sequentially, compressing schedule by 18 calendar days.",
    decisionMakerName: "Sarah Johnson & Col. Thomas Miller",
    decisionMakerTitle: "State Project Director & USACE District Commander",
    organizationsRepresented: ["DOTD", "CPRA", "USACE", "Governor's Office", "SpaceX"],
    statutoryAuthority: "FAST-41 Coordination Agreement & La. R.S. 49:214.30",
    affectedWorkstreamIds: ["WS-WETLANDS-PAD-A", "WS-LA82-HEAVYHAUL"],
    affectedWorkstreamTitles: [
      "Launch Pad A – Wetland & Coastal Authorization",
      "LA-82 Heavy-Haul Access & Bridge Reinforcement",
    ],
    referencedDocumentVersionIds: ["doc-v-drainage-v11", "doc-v-wetland-v4"],
    requiredFollowUps: "CPRA and USACE to hold joint bi-weekly technical synchronization standups.",
  },
  {
    id: "DEC-2026-002",
    projectId: "proj-spacex-pecan",
    decisionDate: "2026-08-22",
    title: "LA-82 Freshwater Bayou Bridge Superload Reinforcement Plan Approval",
    decisionSummary: "Approved steel plate bridge deck reinforcement method and nighttime rolling traffic escort protocol on LA-82.",
    decisionMakerName: "Mark Fontenot, PE",
    decisionMakerTitle: "DOTD District 03 Operations Engineer",
    organizationsRepresented: ["DOTD", "State Police Troop I", "SpaceX"],
    statutoryAuthority: "La. R.S. 32:387 & DOTD Bridge Design Manual Chapter 6",
    affectedWorkstreamIds: ["WS-LA82-HEAVYHAUL"],
    affectedWorkstreamTitles: ["LA-82 Heavy-Haul Access & Bridge Reinforcement"],
    referencedDocumentVersionIds: ["doc-v-drainage-v12"],
  },
];

// ==========================================
// 9. MEETINGS & CONVERSIONS TO OBJECTS
// ==========================================

export const projectMeetingsData: MeetingRecord[] = [
  {
    id: "MTG-2026-0829",
    projectId: "proj-spacex-pecan",
    title: "SpaceX Pecan Island Interagency Delivery Executive Standup",
    meetingDate: "2026-08-29",
    locationOrLink: "Baton Rouge State Capitol / Teams Hybrid",
    attendeeList: [
      "Sarah Johnson (State PM)",
      "Maya Chen (SpaceX)",
      "Mark Fontenot (DOTD)",
      "Jean-Paul Guidry (CPRA)",
      "Dr. Rachel Benoit (LDEQ)",
      "David LeBlanc (Vermilion Parish)",
    ],
    meetingNotes: "Reviewed critical path blockers on LA-82 drainage concurrence and Section 404 Completeness. Established COM-001 for CPRA comments by Sep 5. Approved CR-00451 for fast-tracked review.",
    relatedWorkstreamIds: ["WS-LA82-HEAVYHAUL", "WS-WETLANDS-PAD-A"],
    actionItemsConverted: {
      tasksCreated: 4,
      commitmentsCreated: 2,
      decisionsLogged: 1,
    },
  },
];

// ==========================================
// 10. 9 CORE WORKSTREAMS (DAG GRAPH & DUAL OWNERSHIP)
// ==========================================

export const workstreamsData: WorkstreamRecord[] = [
  {
    id: "WS-LA82-HEAVYHAUL",
    projectId: "proj-spacex-pecan",
    code: "WS-LA82-HEAVYHAUL",
    title: "LA-82 Heavy-Haul Access & Bridge Reinforcement",
    category: "road",
    categoryLabel: "Roads & Access",
    permitTypeId: "cat-dotd-heavyhaul",
    permitTypeCode: "DOTD-HEAVYHAUL",
    currentStageName: "Structural Review & Interagency Concurrence",
    governmentConcierge: {
      name: "Sarah Johnson",
      title: "State Project Concierge",
      agency: "Louisiana Governor's Project Office",
      email: "sarah.johnson@la.gov",
      phone: "(225) 342-7000",
    },
    regulatoryLead: {
      orgCode: "DOTD",
      orgName: "Louisiana Department of Transportation and Development",
      jurisdictionLevel: "State",
      assignedReviewerName: "Mark Fontenot, PE",
      assignedReviewerEmail: "mark.fontenot@dotd.la.gov",
    },
    operationalState: "blocked",
    operationalStateLabel: "Blocked (Interagency Dependency)",
    ragHealth: "red",
    isCriticalPath: true,
    baselineStartDate: "2026-06-01",
    baselineTargetDate: "2026-09-15",
    forecastStartDate: "2026-06-01",
    forecastTargetDate: "2026-09-28",
    scheduleVarianceDays: 13,
    controllingDependencyTitle: "CPRA Drainage & Tidal Concurrence CR-00451",
    currentActionSummary: "Culvert box hydrodynamic and load rating review",
    waitingReason: "Waiting on CPRA coastal drainage concurrence model (CR-00451)",
    waitingOnEntity: "CPRA Coastal Permits",
    nextExpectedEvent: "CPRA Drainage Concurrence Signoff",
    customerActionRequired: "Submit Rev 9 drawing package per RFI-2026-0042 by Sep 3",
    primaryDelayReason: "interagency_dependency",
    delayNotes: "13-day variance driven by CPRA hydrodynamic modeling validation (8d) and axle load RFI cycle (5d).",
    escalationLevel: 2,
    escalationTriggeredAt: "2026-08-28",
    escalationSummary: "Level 2: DOTD Section Supervisor engaged; State PM Sarah Johnson actively mediating.",

    // Milestone 1 ITSM & Assignment Extensions
    assignmentGroupId: "grp-dotd-heavyhaul",
    assignmentGroupName: "DOTD - Structures & Bridge Review",
    assignedToUserId: "user-sam-rivera",
    assignedToUserName: "Sam Rivera",
    assignedOrgCode: "DOTD",
    itsmState: "blocked",
    priority: "P1",
    statutoryDeadline: "2026-09-15",
    clockStatus: "paused",
    clockPausedReason: "Waiting on CPRA coastal drainage concurrence model (CR-00451)",
    clockPausedAt: "2026-08-28T00:00:00Z",
    clockTotalPausedSeconds: 1123200,

    tasks: [
      {
        id: "task-dotd-1",
        workstreamId: "WS-LA82-HEAVYHAUL",
        title: "LA-82 Route Geometric & Turn Radius Analysis",
        taskType: "agency_review",
        assignedOrgId: "org-dotd",
        assignedOrgCode: "DOTD",
        assignedUserName: "Mark Fontenot, PE",
        status: "completed",
        isMilestone: false,
        isCriticalPath: true,
        durationDays: 15,
        floatDays: 0,
        predecessorTaskIds: [],
      },
      {
        id: "task-dotd-2",
        workstreamId: "WS-LA82-HEAVYHAUL",
        title: "Freshwater Bayou Bridge Deck Structural Load Certification",
        taskType: "agency_review",
        assignedOrgId: "org-dotd",
        assignedOrgCode: "DOTD",
        assignedUserName: "Mark Fontenot, PE",
        status: "in_progress",
        isMilestone: false,
        isCriticalPath: true,
        durationDays: 20,
        floatDays: 0,
        predecessorTaskIds: ["task-dotd-1"],
      },
      {
        id: "task-dotd-3",
        workstreamId: "WS-LA82-HEAVYHAUL",
        title: "Culvert 14B Tidal Drainage Concurrence (CR-00451)",
        taskType: "consultation",
        assignedOrgId: "org-cpra",
        assignedOrgCode: "CPRA",
        assignedUserName: "Jean-Paul Guidry",
        status: "blocked",
        isMilestone: true,
        isCriticalPath: true,
        durationDays: 10,
        floatDays: 0,
        predecessorTaskIds: ["task-dotd-2"],
      },
      {
        id: "task-dotd-4",
        workstreamId: "WS-LA82-HEAVYHAUL",
        title: "Final Superload Access Authorization Issuance",
        taskType: "determination",
        assignedOrgId: "org-dotd",
        assignedOrgCode: "DOTD",
        assignedUserName: "Mark Fontenot, PE",
        status: "pending",
        isMilestone: true,
        isCriticalPath: true,
        durationDays: 5,
        floatDays: 0,
        predecessorTaskIds: ["task-dotd-3"],
      },
    ],
    commitments: commitmentsData.filter((c) => c.workstreamId === "WS-LA82-HEAVYHAUL"),
    coordinationRequests: coordinationRequestsData.filter((c) => c.workstreamId === "WS-LA82-HEAVYHAUL"),
    rfis: rfisData.filter((r) => r.workstreamId === "WS-LA82-HEAVYHAUL"),
  },
  {
    id: "WS-WETLANDS-PAD-A",
    projectId: "proj-spacex-pecan",
    code: "WS-WETLANDS-PAD-A",
    title: "Launch Pad A – Wetland & Coastal Authorization",
    category: "permit",
    categoryLabel: "Environmental & Coastal",
    permitTypeId: "cat-usace-404",
    permitTypeCode: "USACE-404",
    currentStageName: "Joint Completeness & Federal 404 Review",
    governmentConcierge: {
      name: "Sarah Johnson",
      title: "State Project Concierge",
      agency: "Louisiana Governor's Project Office",
      email: "sarah.johnson@la.gov",
      phone: "(225) 342-7000",
    },
    regulatoryLead: {
      orgCode: "USACE",
      orgName: "U.S. Army Corps of Engineers — New Orleans District",
      jurisdictionLevel: "Federal",
      assignedReviewerName: "Martin Breaux",
      assignedReviewerEmail: "martin.breaux@usace.army.mil",
    },
    operationalState: "running",
    operationalStateLabel: "Running (Completeness Review)",
    ragHealth: "yellow",
    isCriticalPath: true,
    baselineStartDate: "2026-05-15",
    baselineTargetDate: "2026-10-30",
    forecastStartDate: "2026-05-15",
    forecastTargetDate: "2026-11-06",
    scheduleVarianceDays: 7,
    currentActionSummary: "Section 404 completeness and delineation package review",
    waitingReason: "Awaiting final USACE completeness determination letter (promised Sep 2)",
    waitingOnEntity: "USACE New Orleans District",
    nextExpectedEvent: "Federal 30-day Public Notice Publication",
    customerActionRequired: "None (Delineation polygon shapefile submitted and accepted)",
    primaryDelayReason: "statutory_minimum",
    delayNotes: "7-day variance attributed to joint agency GIS harmonization.",
    escalationLevel: 1,
    escalationSummary: "Level 1: Reviewer SLA active; federal standup on track for Sep 2 letter.",

    // Milestone 1 ITSM & Assignment Extensions
    assignmentGroupId: "grp-cpra-cup",
    assignmentGroupName: "CPRA - Coastal Use & Hydrology Permitting",
    assignedToUserId: "user-jean-paul-guidry",
    assignedToUserName: "Jean-Paul Guidry",
    assignedOrgCode: "CPRA",
    itsmState: "in_progress",
    priority: "P1",
    statutoryDeadline: "2026-10-30",
    clockStatus: "active",
    clockTotalPausedSeconds: 0,

    tasks: [
      {
        id: "task-usace-1",
        workstreamId: "WS-WETLANDS-PAD-A",
        title: "Jurisdictional Wetland Delineation Verification",
        taskType: "agency_review",
        assignedOrgId: "org-usace",
        assignedOrgCode: "USACE",
        assignedUserName: "Martin Breaux",
        status: "completed",
        isMilestone: false,
        isCriticalPath: true,
        durationDays: 30,
        floatDays: 0,
        predecessorTaskIds: [],
      },
      {
        id: "task-usace-2",
        workstreamId: "WS-WETLANDS-PAD-A",
        title: "Section 404 Completeness Determination",
        taskType: "determination",
        assignedOrgId: "org-usace",
        assignedOrgCode: "USACE",
        assignedUserName: "Martin Breaux",
        status: "in_progress",
        isMilestone: true,
        isCriticalPath: true,
        durationDays: 15,
        floatDays: 0,
        predecessorTaskIds: ["task-usace-1"],
      },
      {
        id: "task-usace-3",
        workstreamId: "WS-WETLANDS-PAD-A",
        title: "Federal & State Joint 30-Day Public Notice Period",
        taskType: "public_notice",
        assignedOrgId: "org-usace",
        assignedOrgCode: "USACE",
        status: "pending",
        isMilestone: true,
        isCriticalPath: true,
        durationDays: 30,
        floatDays: 0,
        predecessorTaskIds: ["task-usace-2"],
      },
      {
        id: "task-usace-4",
        workstreamId: "WS-WETLANDS-PAD-A",
        title: "Final 404 Wetland Fill Permit Authorization",
        taskType: "determination",
        assignedOrgId: "org-usace",
        assignedOrgCode: "USACE",
        status: "pending",
        isMilestone: true,
        isCriticalPath: true,
        durationDays: 20,
        floatDays: 0,
        predecessorTaskIds: ["task-usace-3"],
      },
    ],
    commitments: commitmentsData.filter((c) => c.workstreamId === "WS-WETLANDS-PAD-A"),
    coordinationRequests: coordinationRequestsData.filter((c) => c.workstreamId === "WS-WETLANDS-PAD-A"),
    rfis: rfisData.filter((r) => r.workstreamId === "WS-WETLANDS-PAD-A"),
  },
  {
    id: "WS-WASTEWATER-DELUGE",
    projectId: "proj-spacex-pecan",
    code: "WS-WASTEWATER-DELUGE",
    title: "Industrial Wastewater & Launch Deluge Retention Basin",
    category: "permit",
    categoryLabel: "Environmental & Water",
    currentStageName: "Public Hearing & Comment Resolution",
    governmentConcierge: {
      name: "Sarah Johnson",
      title: "State Project Concierge",
      agency: "Louisiana Governor's Project Office",
      email: "sarah.johnson@la.gov",
      phone: "(225) 342-7000",
    },
    regulatoryLead: {
      orgCode: "LDEQ",
      orgName: "Louisiana Department of Environmental Quality",
      jurisdictionLevel: "State",
      assignedReviewerName: "Dr. Rachel Benoit",
      assignedReviewerEmail: "rachel.benoit@la.gov",
    },
    operationalState: "statutory_waiting_period",
    operationalStateLabel: "Statutory Waiting Period (Hearing Follow-up)",
    ragHealth: "yellow",
    isCriticalPath: false,
    baselineStartDate: "2026-05-01",
    baselineTargetDate: "2026-09-30",
    forecastStartDate: "2026-05-01",
    forecastTargetDate: "2026-10-08",
    scheduleVarianceDays: 8,
    currentActionSummary: "Public hearing transcript review & response to public comments",
    waitingReason: "Mandatory statutory 15-day post-hearing public comment closure window",
    waitingOnEntity: "LDEQ Water Permits Engineering Team",
    nextExpectedEvent: "Draft LPDES Permit Delivery (Target Sep 4)",
    customerActionRequired: "None",
    primaryDelayReason: "public_comment",
    delayNotes: "8-day extension to address public questions on deluge retention basin water quality.",
    escalationLevel: 0,

    // Milestone 1 ITSM & Assignment Extensions
    assignmentGroupId: "grp-ldeq-water",
    assignmentGroupName: "LDEQ - Water Quality & Deluge Permitting",
    assignedToUserId: "user-jordan-lee",
    assignedToUserName: "Jordan Lee",
    assignedOrgCode: "LDEQ",
    itsmState: "pending_agency",
    priority: "P2",
    statutoryDeadline: "2026-09-30",
    clockStatus: "paused",
    clockPausedReason: "Public hearing notice and comment resolution",
    clockPausedAt: "2026-08-26T00:00:00Z",
    clockTotalPausedSeconds: 432000,

    tasks: [],
    commitments: commitmentsData.filter((c) => c.workstreamId === "WS-WASTEWATER-DELUGE"),
    coordinationRequests: coordinationRequestsData.filter((c) => c.workstreamId === "WS-WASTEWATER-DELUGE"),
    rfis: [],
  },
  {
    id: "WS-GAS-LNG-PIPELINE",
    projectId: "proj-spacex-pecan",
    code: "WS-GAS-LNG-PIPELINE",
    title: "Natural Gas Supply & Cryogenic LNG Pipeline Interconnect",
    category: "utility",
    categoryLabel: "Utilities & Gas",
    currentStageName: "Route Selection & Pipeline Authority Easements",
    governmentConcierge: {
      name: "Sarah Johnson",
      title: "State Project Concierge",
      agency: "Louisiana Governor's Project Office",
      email: "sarah.johnson@la.gov",
      phone: "(225) 342-7000",
    },
    regulatoryLead: {
      orgCode: "LA-PROJECTS",
      orgName: "Louisiana Pipeline Authority / LPSC",
      jurisdictionLevel: "State",
      assignedReviewerName: "Marcus Vance",
      assignedReviewerEmail: "marcus.vance@lpsc.la.gov",
    },
    operationalState: "running",
    operationalStateLabel: "Running (Easement Negotiation)",
    ragHealth: "green",
    isCriticalPath: true,
    baselineStartDate: "2026-07-01",
    baselineTargetDate: "2026-11-15",
    forecastStartDate: "2026-07-01",
    forecastTargetDate: "2026-11-15",
    scheduleVarianceDays: 0,
    currentActionSummary: "Right-of-way easement survey and parish crossing reviews",
    waitingReason: "Easement alignment coordination standup scheduled for Sep 8",
    waitingOnEntity: "Louisiana State Project Office & Vermilion Parish",
    nextExpectedEvent: "Pipeline Right-of-Way Execution",
    customerActionRequired: "None",
    primaryDelayReason: "none",
    escalationLevel: 0,

    // Milestone 1 ITSM & Assignment Extensions
    assignmentGroupId: "grp-state-po-concierge",
    assignmentGroupName: "Governor's Project Office - Interagency Concierge",
    assignedToUserId: "user-sarah-johnson",
    assignedToUserName: "Sarah Johnson",
    assignedOrgCode: "LA-PROJECTS",
    itsmState: "in_progress",
    priority: "P2",
    statutoryDeadline: "2026-11-15",
    clockStatus: "active",
    clockTotalPausedSeconds: 0,

    tasks: [],
    commitments: commitmentsData.filter((c) => c.workstreamId === "WS-GAS-LNG-PIPELINE"),
    coordinationRequests: [],
    rfis: [],
  },
  {
    id: "WS-SUBSTATION-230KV",
    projectId: "proj-spacex-pecan",
    code: "WS-SUBSTATION-230KV",
    title: "230kV Dual-Feed High-Capacity Grid Interconnect",
    category: "utility",
    categoryLabel: "Utilities & Power",
    currentStageName: "Substation Engineering & Interconnection Agreement",
    governmentConcierge: {
      name: "Sarah Johnson",
      title: "State Project Concierge",
      agency: "Louisiana Governor's Project Office",
      email: "sarah.johnson@la.gov",
      phone: "(225) 342-7000",
    },
    regulatoryLead: {
      orgCode: "LPSC & Entergy",
      orgName: "Entergy Louisiana & Louisiana Public Service Commission",
      jurisdictionLevel: "Utility / Regional",
      assignedReviewerName: "Gregory Hayes, PE",
      assignedReviewerEmail: "ghayes@entergy.com",
    },
    operationalState: "running",
    operationalStateLabel: "Running (On Track)",
    ragHealth: "green",
    isCriticalPath: true,
    baselineStartDate: "2026-04-01",
    baselineTargetDate: "2026-10-15",
    forecastStartDate: "2026-04-01",
    forecastTargetDate: "2026-10-15",
    scheduleVarianceDays: 0,
    currentActionSummary: "Transmission right-of-way clearance and breaker installation",
    waitingReason: "SpaceX delivering transformer impedance parameters by Sep 6",
    waitingOnEntity: "SpaceX Power Engineering",
    nextExpectedEvent: "Dual-Feed Interconnection Agreement Execution",
    customerActionRequired: "Submit transformer impedance parameters (COM-006) by Sep 6",
    primaryDelayReason: "none",
    escalationLevel: 0,

    // Milestone 1 ITSM & Assignment Extensions
    assignmentGroupId: "grp-vermilion-publicworks",
    assignmentGroupName: "Vermilion Parish - Public Works & Drainage",
    assignedToUserId: "user-riley-brooks",
    assignedToUserName: "Riley Brooks",
    assignedOrgCode: "VERMILION-PARISH",
    itsmState: "in_progress",
    priority: "P3",
    statutoryDeadline: "2026-10-15",
    clockStatus: "active",
    clockTotalPausedSeconds: 0,

    tasks: [],
    commitments: commitmentsData.filter((c) => c.workstreamId === "WS-SUBSTATION-230KV"),
    coordinationRequests: [],
    rfis: [],
  },
  {
    id: "WS-PUBLIC-SAFETY-AIRSPACE",
    projectId: "proj-spacex-pecan",
    code: "WS-PUBLIC-SAFETY-AIRSPACE",
    title: "Gulf Airspace & Maritime Safety Corridor",
    category: "public_safety",
    categoryLabel: "Public Safety & Airspace",
    currentStageName: "Federal & State Corridor Interagency Safety Plan",
    governmentConcierge: {
      name: "Sarah Johnson",
      title: "State Project Concierge",
      agency: "Louisiana Governor's Project Office",
      email: "sarah.johnson@la.gov",
      phone: "(225) 342-7000",
    },
    regulatoryLead: {
      orgCode: "State Police / FAA",
      orgName: "Louisiana State Police & FAA Air Traffic Control System Command",
      jurisdictionLevel: "Federal",
      assignedReviewerName: "Capt. Tyler Vance",
      assignedReviewerEmail: "tyler.vance@dps.la.gov",
    },
    operationalState: "running",
    operationalStateLabel: "Running (On Track)",
    ragHealth: "green",
    isCriticalPath: true,
    baselineStartDate: "2026-06-15",
    baselineTargetDate: "2026-11-30",
    forecastStartDate: "2026-06-15",
    forecastTargetDate: "2026-11-30",
    scheduleVarianceDays: 0,
    currentActionSummary: "NOTAM protocol formulation & Coast Guard safety zone boundaries",
    waitingReason: "Parish council resolution for rolling traffic checkpoints (CR-00453)",
    waitingOnEntity: "Vermilion Parish Police Jury",
    nextExpectedEvent: "Joint FAA-USCG-LSP Flight Corridor Protocol Finalization",
    customerActionRequired: "None",
    primaryDelayReason: "none",
    escalationLevel: 0,

    // Milestone 1 ITSM & Assignment Extensions
    assignmentGroupId: "grp-lsp-hazmat",
    assignmentGroupName: "LSP - Emergency Response & Route Clearance",
    assignedToUserId: "user-robert-landry",
    assignedToUserName: "Capt. Robert Landry",
    assignedOrgCode: "LSP",
    itsmState: "in_progress",
    priority: "P2",
    statutoryDeadline: "2026-10-01",
    clockStatus: "active",
    clockTotalPausedSeconds: 0,

    tasks: [],
    commitments: [],
    coordinationRequests: coordinationRequestsData.filter((c) => c.workstreamId === "WS-PUBLIC-SAFETY-AIRSPACE"),
    rfis: [],
  },
  {
    id: "WS-HIGHBAY-OSFM",
    projectId: "proj-spacex-pecan",
    code: "WS-HIGHBAY-OSFM",
    title: "Starship High-Bay Building & Fire Marshal Review",
    category: "public_safety",
    categoryLabel: "Construction & Fire Safety",
    currentStageName: "Cryogenic High-Bay Life Safety Review",
    governmentConcierge: {
      name: "Sarah Johnson",
      title: "State Project Concierge",
      agency: "Louisiana Governor's Project Office",
      email: "sarah.johnson@la.gov",
      phone: "(225) 342-7000",
    },
    regulatoryLead: {
      orgCode: "OSFM",
      orgName: "Louisiana Office of State Fire Marshal",
      jurisdictionLevel: "State",
      assignedReviewerName: "Chief Dan Thibodeaux",
      assignedReviewerEmail: "dan.thibodeaux@dps.la.gov",
    },
    operationalState: "running",
    operationalStateLabel: "Running (Reviewing Plans)",
    ragHealth: "green",
    isCriticalPath: false,
    baselineStartDate: "2026-07-10",
    baselineTargetDate: "2026-09-25",
    forecastStartDate: "2026-07-10",
    forecastTargetDate: "2026-09-25",
    scheduleVarianceDays: 0,
    currentActionSummary: "High-bay cryogenic detection and deluge sprinkler plan review",
    waitingReason: "Internal OSFM engineering plan signoff",
    waitingOnEntity: "Office of State Fire Marshal",
    nextExpectedEvent: "Certificate of Plan Approval Issuance",
    customerActionRequired: "None",
    primaryDelayReason: "none",
    escalationLevel: 0,

    // Milestone 1 ITSM & Assignment Extensions
    assignmentGroupId: "grp-osfm-lifesafety",
    assignmentGroupName: "OSFM - Life Safety & Plan Review",
    assignedToUserId: "user-dan-thibodeaux",
    assignedToUserName: "Chief Dan Thibodeaux",
    assignedOrgCode: "OSFM",
    itsmState: "resolved",
    priority: "P3",
    statutoryDeadline: "2026-08-15",
    clockStatus: "stopped",
    clockTotalPausedSeconds: 0,

    tasks: [],
    commitments: [],
    coordinationRequests: [],
    rfis: [],
  },
  {
    id: "WS-WORKFORCE-CONSORTIUM",
    projectId: "proj-spacex-pecan",
    code: "WS-WORKFORCE-CONSORTIUM",
    title: "South Louisiana Aerospace Specialized Workforce Pipeline",
    category: "workforce",
    categoryLabel: "Workforce Training",
    currentStageName: "FastStart Aerospace Curriculum Rollout",
    governmentConcierge: {
      name: "Sarah Johnson",
      title: "State Project Concierge",
      agency: "Louisiana Governor's Project Office",
      email: "sarah.johnson@la.gov",
      phone: "(225) 342-7000",
    },
    regulatoryLead: {
      orgCode: "LED FastStart",
      orgName: "Louisiana Economic Development & South Louisiana Community College",
      jurisdictionLevel: "State",
      assignedReviewerName: "Paul Helton",
      assignedReviewerEmail: "paul.helton@la.gov",
    },
    operationalState: "complete",
    operationalStateLabel: "Complete (Active Program)",
    ragHealth: "green",
    isCriticalPath: false,
    baselineStartDate: "2026-03-01",
    baselineTargetDate: "2026-08-01",
    forecastStartDate: "2026-03-01",
    forecastTargetDate: "2026-08-01",
    actualCompletionDate: "2026-08-01",
    scheduleVarianceDays: 0,
    currentActionSummary: "Aerospace technician training cohort in session at SLCC Lafayette Campus",
    waitingReason: "Cohort 1 graduating in October",
    waitingOnEntity: "LED & SLCC",
    nextExpectedEvent: "Cohort 1 Apprenticeship Placement",
    customerActionRequired: "None",
    primaryDelayReason: "none",
    escalationLevel: 0,

    // Milestone 1 ITSM & Assignment Extensions
    assignmentGroupId: "grp-state-po-concierge",
    assignmentGroupName: "Governor's Project Office - Interagency Concierge",
    assignedToUserId: "user-sarah-johnson",
    assignedToUserName: "Sarah Johnson",
    assignedOrgCode: "LA-PROJECTS",
    itsmState: "in_progress",
    priority: "P4",
    statutoryDeadline: "2026-12-01",
    clockStatus: "active",
    clockTotalPausedSeconds: 0,

    tasks: [],
    commitments: [],
    coordinationRequests: [],
    rfis: [],
  },
  {
    id: "WS-PREAPP-SUBSTATION-PH2",
    projectId: "proj-spacex-pecan",
    code: "WS-PREAPP-SUBSTATION-PH2",
    title: "Pre-Application: 230kV Substation Expansion Phase II",
    category: "utility",
    categoryLabel: "Pre-Application Coordination",
    currentStageName: "Pre-Application Readiness & Study Formulation",
    governmentConcierge: {
      name: "Sarah Johnson",
      title: "State Project Concierge",
      agency: "Louisiana Governor's Project Office",
      email: "sarah.johnson@la.gov",
      phone: "(225) 342-7000",
    },
    regulatoryLead: {
      orgCode: "LPSC & Entergy",
      orgName: "Louisiana Public Service Commission / Entergy",
      jurisdictionLevel: "Utility / Regional",
      assignedReviewerName: "Gregory Hayes, PE",
      assignedReviewerEmail: "ghayes@entergy.com",
    },
    operationalState: "running",
    operationalStateLabel: "Pre-Application Coordination (86% Ready)",
    ragHealth: "green",
    isCriticalPath: false,
    baselineStartDate: "2026-08-01",
    baselineTargetDate: "2026-12-01",
    forecastStartDate: "2026-08-01",
    forecastTargetDate: "2026-12-01",
    scheduleVarianceDays: 0,
    currentActionSummary: "Pre-application study formulation & readiness checklist verification",
    waitingReason: "SpaceX finalizing cultural resources archeological survey",
    waitingOnEntity: "SpaceX Environmental Consultants",
    nextExpectedEvent: "Formal Filing Submission (Target Oct 1)",
    customerActionRequired: "Complete Cultural Resources Survey",
    primaryDelayReason: "none",
    escalationLevel: 0,

    // Milestone 1 ITSM & Assignment Extensions
    assignmentGroupId: "grp-spacex-reg",
    assignmentGroupName: "SpaceX - Regulatory Affairs Queue",
    assignedToUserId: "user-maya-chen",
    assignedToUserName: "Maya Chen",
    assignedOrgCode: "SPACEX",
    itsmState: "draft",
    priority: "P3",
    statutoryDeadline: "2026-12-15",
    clockStatus: "active",
    clockTotalPausedSeconds: 0,

    readinessChecklist: {
      id: "rc-sub-ph2",
      workstreamId: "WS-PREAPP-SUBSTATION-PH2",
      workstreamTitle: "Pre-Application: 230kV Substation Expansion Phase II",
      phase: "pre_application",
      overallReadinessPercent: 86,
      targetFilingDate: "2026-10-01",
      items: [
        {
          id: "rci-1",
          checklistId: "rc-sub-ph2",
          itemName: "Electrical Engineering Single-Line Drawings",
          status: "ready",
          assignedParty: "SpaceX",
          notes: "Approved by SpaceX Chief Power Engineer.",
        },
        {
          id: "rci-2",
          checklistId: "rc-sub-ph2",
          itemName: "Jurisdictional Wetland Delineation",
          status: "ready",
          assignedParty: "Consultant (Gretna Environmental)",
          notes: "Confirmed zero coastal marsh impact for switchyard pad.",
        },
        {
          id: "rci-3",
          checklistId: "rc-sub-ph2",
          itemName: "Alternatives Transmission Routing Analysis",
          status: "ready",
          assignedParty: "SpaceX",
          notes: "Selected least-impact corridor along existing canal right-of-way.",
        },
        {
          id: "rci-4",
          checklistId: "rc-sub-ph2",
          itemName: "Phase I Cultural Resources & Archaeological Survey",
          status: "underway",
          assignedParty: "Consultant",
          notes: "Field shovel testing 75% complete; final report due Sep 12.",
        },
        {
          id: "rci-5",
          checklistId: "rc-sub-ph2",
          itemName: "Formal LPSC Section 85 Application Form",
          status: "ready",
          assignedParty: "Legal Counsel",
        },
        {
          id: "rci-6",
          checklistId: "rc-sub-ph2",
          itemName: "Statutory Filing Fee Remittance",
          status: "ready",
          assignedParty: "SpaceX Finance",
        },
      ],
    },
    tasks: [],
    commitments: [],
    coordinationRequests: [],
    rfis: [],
  },
];

// ==========================================
// 11. COMPLETE PROJECT RECORD (SPACEX PECAN ISLAND)
// ==========================================

export const spacexProjectRecord: ProjectRecord = {
  id: "proj-spacex-pecan",
  code: "SPACEX-PECAN-ISLAND",
  name: "SpaceX Pecan Island Launch Complex & Orbital Support Facility",
  applicantOrgCode: "SPACEX",
  leadStateAgencyCode: "LA-PROJECTS",
  stateProjectManagerName: "Sarah Johnson (Louisiana State Project Director)",
  customerProgramManagerName: "Maya Chen (SpaceX Director of Launch Site Operations)",
  locationDescription: "Pecan Island Coastal Zone, Vermilion Parish, Louisiana",
  parish: "Vermilion Parish",
  baselineLaunchDate: "2026-12-15",
  currentForecastLaunchDate: "2026-12-28",
  scheduleVarianceDays: 13,
  overallRagHealth: "yellow",
  workstreams: workstreamsData,
  commitments: commitmentsData,
  decisions: projectDecisionsData,
  meetings: projectMeetingsData,
  documents: projectDocumentsData,
  coordinationRequests: coordinationRequestsData,
  auditLedger: [
    {
      id: "audit-001",
      entityType: "coordination_request",
      entityId: "CR-00451",
      actorName: "Mark Fontenot, PE",
      actorOrgName: "DOTD District 03",
      actionType: "created",
      newValue: "Requested CPRA drainage concurrence for LA-82 Box Culverts",
      reason: "Mandatory statutory coastal concurrence before heavy-haul permit release",
      sourceChannel: "web_app",
      occurredAt: "2026-08-29T09:15:00Z",
    },
    {
      id: "audit-002",
      entityType: "commitment",
      entityId: "COM-001",
      actorName: "Jean-Paul Guidry",
      actorOrgName: "CPRA Coastal Permits",
      actionType: "committed",
      newValue: "Promised consolidated comments by Sep 5",
      reason: "Agreed during Aug 29 Interagency Executive Standup",
      sourceChannel: "web_app",
      occurredAt: "2026-08-29T10:45:00Z",
    },
    {
      id: "audit-003",
      entityType: "rfi",
      entityId: "RFI-2026-0042",
      actorName: "Mark Fontenot, PE",
      actorOrgName: "DOTD",
      actionType: "issued",
      newValue: "Requested Bridge Load Analysis & Dual-Trailer Drawing",
      reason: "Bridge Bureau deck flexure compliance",
      sourceChannel: "web_app",
      occurredAt: "2026-08-29T14:30:00Z",
    },
  ],
};
