/** Typed mirror of the canonical Supabase/Postgres command schema.
 * Executable migrations live under supabase/migrations. */
import { boolean, date, integer, jsonb, pgTable, primaryKey, text, timestamp, uuid } from "drizzle-orm/pg-core";

const id = () => uuid("id").defaultRandom().primaryKey();
const createdAt = timestamp("created_at", { withTimezone: true }).defaultNow().notNull();
const updatedAt = timestamp("updated_at", { withTimezone: true }).defaultNow().notNull();

export const organizations = pgTable("organizations", { id: id(), code: text("code").notNull(), name: text("name").notNull(), jurisdictionLevel: text("jurisdiction_level").notNull(), active: boolean("active").default(true).notNull(), createdAt, updatedAt });
export const organizationalUnits = pgTable("organizational_units", { id: id(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), code: text("code").notNull(), name: text("name").notNull(), parentUnitId: uuid("parent_unit_id"), createdAt, updatedAt });
export const users = pgTable("profiles", { id: uuid("id").primaryKey(), email: text("email"), fullName: text("full_name"), organizationId: uuid("organization_id"), unitId: uuid("unit_id"), status: text("status").notNull(), createdAt, updatedAt });
export const organizationMemberships = pgTable("organization_memberships", { id: id(), userId: uuid("user_id").notNull().references(() => users.id), organizationId: uuid("organization_id").notNull().references(() => organizations.id), role: text("role").notNull(), status: text("status").notNull(), createdAt, updatedAt });
export const capabilities = pgTable("capabilities", { id: id(), code: text("code").notNull(), name: text("name").notNull(), createdAt, updatedAt });
export const membershipCapabilities = pgTable("membership_capabilities", { membershipId: uuid("membership_id").notNull().references(() => organizationMemberships.id), capabilityId: uuid("capability_id").notNull().references(() => capabilities.id) }, t => [primaryKey({ columns: [t.membershipId, t.capabilityId] })]);
export const projects = pgTable("projects", { id: id(), number: text("number").notNull(), name: text("name").notNull(), customerOrganizationId: uuid("customer_organization_id"), leadOrganizationId: uuid("lead_organization_id").notNull().references(() => organizations.id), status: text("status").notNull(), baselineLaunchDate: date("baseline_launch_date"), forecastLaunchDate: date("forecast_launch_date"), createdAt, updatedAt });
export const projectParticipants = pgTable("project_participants", { id: id(), projectId: uuid("project_id").notNull().references(() => projects.id), organizationId: uuid("organization_id").notNull().references(() => organizations.id), participationRole: text("participation_role").notNull(), accessScope: text("access_scope").notNull(), createdAt, updatedAt });
export const permitTypes = pgTable("permit_types", { id: id(), code: text("code").notNull(), name: text("name").notNull(), category: text("category").notNull(), responsibleOrgId: uuid("responsible_organization_id").notNull().references(() => organizations.id), officialFilingUrl: text("official_filing_url"), statutoryAuthority: text("statutory_authority"), createdAt, updatedAt });
export const requirementResources = pgTable("requirement_resources", { id: id(), permitTypeId: uuid("permit_type_id").notNull().references(() => permitTypes.id), name: text("name").notNull(), resourceType: text("resource_type").notNull(), url: text("url").notNull(), versionTag: text("version_tag").notNull(), verifiedAt: timestamp("verified_at", { withTimezone: true }).notNull(), createdAt, updatedAt });
export const workflowTemplates = pgTable("workflow_templates", { id: id(), permitTypeId: uuid("permit_type_id").references(() => permitTypes.id), organizationId: uuid("organization_id").notNull().references(() => organizations.id), name: text("name").notNull(), createdAt, updatedAt });
export const workflowVersions = pgTable("workflow_versions", { id: id(), templateId: uuid("template_id").notNull().references(() => workflowTemplates.id), versionNumber: integer("version_number").notNull(), status: text("status").notNull(), publishedAt: timestamp("published_at", { withTimezone: true }), createdAt, updatedAt });
export const workflowStages = pgTable("workflow_stages", { id: id(), workflowVersionId: uuid("workflow_version_id").notNull().references(() => workflowVersions.id), stageKey: text("stage_key").notNull(), name: text("name").notNull(), responsibleOrganizationId: uuid("responsible_organization_id").references(() => organizations.id), targetDurationDays: integer("target_duration_days").notNull(), minimumStatutoryDays: integer("minimum_statutory_days").notNull().default(0), createdAt, updatedAt });
export const workflowTransitions = pgTable("workflow_transitions", { id: id(), workflowVersionId: uuid("workflow_version_id").notNull().references(() => workflowVersions.id), fromStageId: uuid("from_stage_id").notNull().references(() => workflowStages.id), toStageId: uuid("to_stage_id").notNull().references(() => workflowStages.id), gateType: text("gate_type").notNull().default("AND"), createdAt, updatedAt });
export const workflowStageRequirements = pgTable("workflow_stage_requirements", { id: id(), workflowStageId: uuid("workflow_stage_id").notNull().references(() => workflowStages.id), requirementType: text("requirement_type").notNull(), requirementKey: text("requirement_key").notNull(), createdAt, updatedAt });
export const workflowInstances = pgTable("workflow_instances", { id: id(), workstreamId: uuid("workstream_id").notNull(), workflowVersionId: uuid("workflow_version_id").notNull().references(() => workflowVersions.id), currentStageId: uuid("current_stage_id").references(() => workflowStages.id), clockState: text("clock_state").notNull(), createdAt, updatedAt });
export const workstreams = pgTable("workstreams", { id: id(), projectId: uuid("project_id").notNull().references(() => projects.id), code: text("code").notNull(), title: text("title").notNull(), regulatoryLeadOrgId: uuid("lead_organization_id").notNull().references(() => organizations.id), governmentConciergeUserId: uuid("government_concierge_user_id").references(() => users.id), assignedReviewerUserId: uuid("assigned_reviewer_user_id").references(() => users.id), ownerUserId: uuid("owner_user_id").references(() => users.id), state: text("state").notNull(), currentAction: text("current_action"), waitingOnType: text("waiting_on_type"), waitingOnId: uuid("waiting_on_id"), nextActionDueAt: timestamp("next_action_due_at", { withTimezone: true }), missedDateConsequence: text("missed_date_consequence"), baselineTargetDate: date("baseline_target_date").notNull(), forecastTargetDate: date("forecast_target_date").notNull(), actualCompletionDate: date("actual_completion_date"), isCriticalPath: boolean("is_critical_path").notNull().default(false), createdAt, updatedAt });
export const tasks = pgTable("tasks", { id: id(), workstreamId: uuid("workstream_id").notNull().references(() => workstreams.id), title: text("title").notNull(), assignedOrganizationId: uuid("assigned_organization_id").notNull().references(() => organizations.id), assignedUserId: uuid("assigned_user_id").references(() => users.id), status: text("status").notNull(), baselineStartDate: date("baseline_start_date"), baselineDueDate: date("baseline_due_date"), forecastStartDate: date("forecast_start_date"), forecastDueDate: date("forecast_due_date"), actualCompletionDate: date("actual_completion_date"), durationDays: integer("duration_days").notNull().default(1), createdAt, updatedAt });
export const taskDependencies = pgTable("task_dependencies", { id: id(), predecessorTaskId: uuid("predecessor_task_id").notNull().references(() => tasks.id), successorTaskId: uuid("successor_task_id").notNull().references(() => tasks.id), dependencyType: text("dependency_type").notNull(), gateType: text("gate_type").notNull(), lagDays: integer("lag_days").notNull().default(0), createdAt, updatedAt });
export const commitments = pgTable("commitments", { id: id(), workstreamId: uuid("workstream_id").notNull().references(() => workstreams.id), organizationId: uuid("organization_id").notNull().references(() => organizations.id), action: text("action").notNull(), dueDate: date("due_date").notNull(), status: text("status").notNull(), createdAt, updatedAt });
export const coordinationRequests = pgTable("coordination_requests", { id: id(), code: text("code").notNull(), workstreamId: uuid("workstream_id").notNull().references(() => workstreams.id), requestingOrganizationId: uuid("requesting_organization_id").notNull().references(() => organizations.id), targetOrganizationId: uuid("target_organization_id").notNull().references(() => organizations.id), title: text("title").notNull(), dueDate: date("due_date").notNull(), status: text("status").notNull(), createdAt, updatedAt });
export const rfis = pgTable("rfis", { id: id(), code: text("code").notNull(), workstreamId: uuid("workstream_id").notNull().references(() => workstreams.id), requestingOrganizationId: uuid("requesting_organization_id").notNull().references(() => organizations.id), recipientOrganizationId: uuid("recipient_organization_id").notNull().references(() => organizations.id), status: text("status").notNull(), clockImpact: text("clock_impact").notNull(), dueDate: date("due_date").notNull(), createdAt, updatedAt });
export const rfiItems = pgTable("rfi_items", { id: id(), rfiId: uuid("rfi_id").notNull().references(() => rfis.id), question: text("question").notNull(), status: text("status").notNull(), createdAt, updatedAt });
export const rfiResponses = pgTable("rfi_responses", { id: id(), rfiId: uuid("rfi_id").notNull().references(() => rfis.id), responseText: text("response_text").notNull(), status: text("status").notNull(), submittedBy: uuid("submitted_by").references(() => users.id), createdAt, updatedAt });
export const documents = pgTable("documents", { id: id(), projectId: uuid("project_id").notNull().references(() => projects.id), ownerOrganizationId: uuid("owner_organization_id").notNull().references(() => organizations.id), title: text("title").notNull(), classification: text("classification").notNull(), retentionCategory: text("retention_category"), createdAt, updatedAt });
export const documentVersions = pgTable("document_versions", { id: id(), documentId: uuid("document_id").notNull().references(() => documents.id), versionNumber: integer("version_number").notNull(), storagePath: text("storage_path").notNull(), sha256: text("sha256"), scanStatus: text("scan_status").notNull(), uploadedBy: uuid("uploaded_by").references(() => users.id), createdAt, updatedAt });
export const documentReferences = pgTable("document_references", { id: id(), documentVersionId: uuid("document_version_id").notNull().references(() => documentVersions.id), entityType: text("entity_type").notNull(), entityId: uuid("entity_id").notNull(), createdAt, updatedAt });
export const documentAgencyReviews = pgTable("document_agency_reviews", { id: id(), documentVersionId: uuid("document_version_id").notNull().references(() => documentVersions.id), reviewingOrganizationId: uuid("reviewing_organization_id").notNull().references(() => organizations.id), status: text("status").notNull(), createdAt, updatedAt });
export const decisions = pgTable("decisions", { id: id(), projectId: uuid("project_id").notNull().references(() => projects.id), title: text("title").notNull(), decision: text("decision").notNull(), authority: text("authority"), createdAt, updatedAt });
export const meetings = pgTable("meetings", { id: id(), projectId: uuid("project_id").notNull().references(() => projects.id), title: text("title").notNull(), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(), notes: text("notes"), createdAt, updatedAt });
export const meetingActions = pgTable("meeting_actions", { id: id(), meetingId: uuid("meeting_id").notNull().references(() => meetings.id), entityType: text("entity_type").notNull(), entityId: uuid("entity_id").notNull(), createdAt, updatedAt });
export const readinessChecklists = pgTable("readiness_checklists", { id: id(), workstreamId: uuid("workstream_id").notNull().references(() => workstreams.id), targetFilingDate: date("target_filing_date"), createdAt, updatedAt });
export const readinessItems = pgTable("readiness_items", { id: id(), checklistId: uuid("checklist_id").notNull().references(() => readinessChecklists.id), name: text("name").notNull(), status: text("status").notNull(), createdAt, updatedAt });
export const escalationPolicies = pgTable("escalation_policies", { id: id(), organizationId: uuid("organization_id").notNull().references(() => organizations.id), name: text("name").notNull(), thresholds: jsonb("thresholds").notNull(), createdAt, updatedAt });
export const escalationEvents = pgTable("escalation_events", { id: id(), workstreamId: uuid("workstream_id").notNull().references(() => workstreams.id), policyId: uuid("policy_id").references(() => escalationPolicies.id), level: text("level").notNull(), status: text("status").notNull(), createdAt, updatedAt });
export const notifications = pgTable("notifications", { id: id(), recipientId: uuid("recipient_id").notNull().references(() => users.id), eventType: text("event_type").notNull(), title: text("title").notNull(), body: text("body").notNull(), deliveryStatus: text("delivery_status").notNull(), createdAt, updatedAt });
export const auditEvents = pgTable("audit_events", { id: id(), actorId: uuid("actor_id").references(() => users.id), organizationId: uuid("organization_id").references(() => organizations.id), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: uuid("entity_id"), beforeState: jsonb("before_state"), afterState: jsonb("after_state"), reason: text("reason"), correlationId: uuid("correlation_id").notNull().defaultRandom(), createdAt });

// Compatibility aliases retain the established domain vocabulary while the
// physical Postgres column names remain concise and normalized.
Object.assign(workflowStages, { responsibleOrgId: workflowStages.responsibleOrganizationId });
Object.assign(projects, { applicantOrgId: projects.customerOrganizationId, leadStateAgencyId: projects.leadOrganizationId });
Object.assign(requirementResources, { isStale: requirementResources.verifiedAt });
Object.assign(workstreams, { currentActionSummary: workstreams.currentAction, waitingReason: workstreams.waitingOnType, waitingOnEntity: workstreams.waitingOnType, nextExpectedEvent: workstreams.nextActionDueAt, customerActionRequired: workstreams.missedDateConsequence });
Object.assign(tasks, { assignedOrgId: tasks.assignedOrganizationId });
Object.assign(commitments, { committingOrgId: commitments.organizationId });
Object.assign(coordinationRequests, { requestingOrgId: coordinationRequests.requestingOrganizationId, targetOrgId: coordinationRequests.targetOrganizationId, blocksWorkstreamTitle: coordinationRequests.title });
Object.assign(rfis, { requestingOrgId: rfis.requestingOrganizationId, recipientOrgId: rfis.recipientOrganizationId, isConsolidatedCycle: rfis.clockImpact, consolidatedBatchId: rfis.id });
Object.assign(documents, { ownerOrgId: documents.ownerOrganizationId });
Object.assign(documentVersions, { sha256Hash: documentVersions.sha256, versionTag: documentVersions.versionNumber, storageUri: documentVersions.storagePath });
Object.assign(documentAgencyReviews, { workstreamId: documentAgencyReviews.documentVersionId, reviewingOrgId: documentAgencyReviews.reviewingOrganizationId });
Object.assign(auditEvents, { actionType: auditEvents.action, sourceChannel: auditEvents.reason, occurredAt: auditEvents.createdAt });
