-- PATH command-system persistence foundation. This is additive to the legacy
-- request MVP and establishes Supabase Postgres as the only operational store.
-- The old D1 schema was never deployed and is intentionally not migrated.

create extension if not exists pgcrypto;

-- The legacy workflow/doc tables had incompatible one-row version models.
alter table if exists public.workflow_stages rename to legacy_workflow_stages;
alter table if exists public.documents rename to legacy_documents;

alter table public.organizations add column if not exists parent_organization_id uuid references public.organizations(id);
alter table public.organizations add column if not exists archived_at timestamptz;
alter table public.profiles add column if not exists organization_id uuid references public.organizations(id);
alter table public.profiles add column if not exists unit_id uuid;
alter table public.projects add column if not exists baseline_launch_date date;
alter table public.projects add column if not exists forecast_launch_date date;

create table if not exists public.organizational_units (
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), code text not null, name text not null, parent_unit_id uuid references public.organizational_units(id), archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id, code)
);
create table if not exists public.capabilities (id uuid primary key default gen_random_uuid(), code text not null unique, name text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.membership_capabilities (membership_id uuid not null references public.organization_memberships(id) on delete cascade, capability_id uuid not null references public.capabilities(id) on delete cascade, primary key(membership_id, capability_id));

create table if not exists public.permit_types (
 id uuid primary key default gen_random_uuid(), code text not null unique, name text not null, category text not null check(category in ('permit','road','utility','public_safety','workforce','community')), responsible_organization_id uuid not null references public.organizations(id), trigger_explanation text, official_filing_url text, statutory_authority text, expected_review_days integer check(expected_review_days >= 0), minimum_statutory_days integer not null default 0 check(minimum_statutory_days >= 0), archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.requirement_resources (
 id uuid primary key default gen_random_uuid(), permit_type_id uuid not null references public.permit_types(id) on delete cascade, name text not null, resource_type text not null, url text not null, version_tag text not null, instructions text, source_authority text, verified_at timestamptz not null, verified_by uuid references public.profiles(id), stale_after timestamptz, superseded_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.permit_type_relations (permit_type_id uuid not null references public.permit_types(id) on delete cascade, related_permit_type_id uuid not null references public.permit_types(id), relation_type text not null check(relation_type in ('prerequisite','related')), primary key(permit_type_id, related_permit_type_id, relation_type));

create table if not exists public.workflow_templates (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), permit_type_id uuid references public.permit_types(id), name text not null, description text, archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.workflow_versions (id uuid primary key default gen_random_uuid(), template_id uuid not null references public.workflow_templates(id) on delete cascade, version_number integer not null check(version_number > 0), status text not null check(status in ('DRAFT','PUBLISHED','RETIRED')), published_at timestamptz, published_by uuid references public.profiles(id), change_summary text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(template_id, version_number));
create table if not exists public.workflow_stages (id uuid primary key default gen_random_uuid(), workflow_version_id uuid not null references public.workflow_versions(id) on delete cascade, stage_key text not null, name text not null, customer_label text not null, responsible_organization_id uuid references public.organizations(id), responsible_unit_id uuid references public.organizational_units(id), target_duration_days integer not null check(target_duration_days >= 0), minimum_statutory_days integer not null default 0 check(minimum_statutory_days >= 0), parallel_allowed boolean not null default false, milestone_gate boolean not null default false, external_filing_url text, legal_authority text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(workflow_version_id, stage_key));
create table if not exists public.workflow_transitions (id uuid primary key default gen_random_uuid(), workflow_version_id uuid not null references public.workflow_versions(id) on delete cascade, from_stage_id uuid not null references public.workflow_stages(id), to_stage_id uuid not null references public.workflow_stages(id), gate_type text not null default 'AND' check(gate_type in ('AND','OR')), condition_expression text, required_capability_code text, created_at timestamptz not null default now(), unique(workflow_version_id, from_stage_id, to_stage_id));
create table if not exists public.workflow_stage_requirements (id uuid primary key default gen_random_uuid(), workflow_stage_id uuid not null references public.workflow_stages(id) on delete cascade, requirement_type text not null check(requirement_type in ('input','completion','document')), requirement_key text not null, required boolean not null default true, created_at timestamptz not null default now(), unique(workflow_stage_id, requirement_type, requirement_key));

create table if not exists public.workstreams (
 id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete cascade, code text not null, title text not null, permit_type_id uuid references public.permit_types(id), workflow_version_id uuid references public.workflow_versions(id), lead_organization_id uuid not null references public.organizations(id), government_concierge_user_id uuid references public.profiles(id), assigned_reviewer_user_id uuid references public.profiles(id), owner_user_id uuid references public.profiles(id), state text not null check(state in ('running','waiting_government','waiting_applicant','waiting_external','scheduled_hold','statutory_waiting_period','blocked','escalated','complete','cancelled')), current_action text, waiting_on_type text check(waiting_on_type in ('coordination_request','rfi','external_filing','other')), waiting_on_id uuid, waiting_reason text, next_action_due_at timestamptz, missed_date_consequence text, baseline_target_date date not null, forecast_target_date date not null, actual_completion_date date, is_critical_path boolean not null default false, archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(project_id,code), check ((state in ('complete','cancelled')) or ((owner_user_id is not null and current_action is not null) or (waiting_on_type is not null and waiting_reason is not null and next_action_due_at is not null)))
);
create table if not exists public.workflow_instances (id uuid primary key default gen_random_uuid(), workstream_id uuid not null unique references public.workstreams(id) on delete cascade, workflow_version_id uuid not null references public.workflow_versions(id), current_stage_id uuid references public.workflow_stages(id), clock_state text not null check(clock_state in ('running','paused','extended','complete')), clock_paused_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.tasks (id uuid primary key default gen_random_uuid(), workstream_id uuid not null references public.workstreams(id) on delete cascade, title text not null, assigned_organization_id uuid not null references public.organizations(id), assigned_user_id uuid references public.profiles(id), status text not null check(status in ('pending','in_progress','waiting','blocked','completed','waived')), baseline_start_date date, baseline_due_date date, forecast_start_date date, forecast_due_date date, actual_completion_date date, duration_days integer not null default 1 check(duration_days >= 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index if not exists tasks_workstream_title_uq on public.tasks(workstream_id,title);
create table if not exists public.task_dependencies (id uuid primary key default gen_random_uuid(), predecessor_task_id uuid not null references public.tasks(id) on delete cascade, successor_task_id uuid not null references public.tasks(id) on delete cascade, dependency_type text not null check(dependency_type in ('finish_to_start','start_to_start','finish_to_finish')), gate_type text not null default 'AND' check(gate_type in ('AND','OR')), lag_days integer not null default 0, created_at timestamptz not null default now(), unique(predecessor_task_id, successor_task_id), check(predecessor_task_id <> successor_task_id));

create table if not exists public.commitments (id uuid primary key default gen_random_uuid(), workstream_id uuid not null references public.workstreams(id), organization_id uuid not null references public.organizations(id), made_by uuid references public.profiles(id), action text not null, origin_context text, promised_date date, due_date date not null, status text not null check(status in ('on_track','at_risk','fulfilled','missed','waived')), impact_if_missed text not null, critical_path_impact boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.coordination_requests (id uuid primary key default gen_random_uuid(), code text not null unique, workstream_id uuid not null references public.workstreams(id), requesting_organization_id uuid not null references public.organizations(id), target_organization_id uuid not null references public.organizations(id), assigned_to uuid references public.profiles(id), title text not null, need_description text not null, due_date date not null, response_summary text, status text not null check(status in ('pending','in_review','concurred','objection_raised','closed')), priority text not null default 'normal' check(priority in ('normal','high','critical_path')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(requesting_organization_id <> target_organization_id));
create table if not exists public.rfis (id uuid primary key default gen_random_uuid(), code text not null unique, workstream_id uuid not null references public.workstreams(id), requesting_organization_id uuid not null references public.organizations(id), recipient_organization_id uuid not null references public.organizations(id), title text not null, status text not null check(status in ('draft','staged','issued','partial_response','submitted','accepted','clarification','rejected','withdrawn','overdue')), clock_impact text not null check(clock_impact in ('pause','run','extend')), due_date date not null, consolidated_batch_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.rfi_items (id uuid primary key default gen_random_uuid(), rfi_id uuid not null references public.rfis(id) on delete cascade, question text not null, status text not null default 'open', created_at timestamptz not null default now());
create table if not exists public.rfi_responses (id uuid primary key default gen_random_uuid(), rfi_id uuid not null references public.rfis(id) on delete cascade, submitted_by uuid references public.profiles(id), response_text text not null, status text not null check(status in ('submitted','accepted','clarification','rejected')), reviewed_by uuid references public.profiles(id), reviewed_at timestamptz, created_at timestamptz not null default now());

create table if not exists public.documents (id uuid primary key default gen_random_uuid(), external_seed_key text unique, project_id uuid not null references public.projects(id), owner_organization_id uuid not null references public.organizations(id), title text not null, classification text not null check(classification in ('public','customer','participant','restricted')), retention_category text, archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.document_versions (id uuid primary key default gen_random_uuid(), document_id uuid not null references public.documents(id) on delete restrict, version_number integer not null check(version_number > 0), file_name text not null, mime_type text not null, file_size_bytes bigint not null check(file_size_bytes >= 0), storage_path text not null unique, sha256 text, scan_status text not null check(scan_status in ('pending','clean','blocked','failed')), uploaded_by uuid references public.profiles(id), created_at timestamptz not null default now(), unique(document_id,version_number));
create table if not exists public.document_references (id uuid primary key default gen_random_uuid(), document_version_id uuid not null references public.document_versions(id), entity_type text not null, entity_id uuid not null, created_at timestamptz not null default now(), unique(document_version_id,entity_type,entity_id));
create table if not exists public.document_agency_reviews (id uuid primary key default gen_random_uuid(), document_version_id uuid not null references public.document_versions(id), reviewing_organization_id uuid not null references public.organizations(id), status text not null check(status in ('under_review','approved','approved_with_conditions','revision_requested','waived')), reviewed_by uuid references public.profiles(id), reviewed_at timestamptz, comments text, created_at timestamptz not null default now(), unique(document_version_id,reviewing_organization_id));
create table if not exists public.decisions (id uuid primary key default gen_random_uuid(), external_seed_key text unique, project_id uuid not null references public.projects(id), title text not null, decision text not null, authority text, decided_by uuid references public.profiles(id), decided_at timestamptz not null default now(), created_at timestamptz not null default now());
create table if not exists public.meetings (id uuid primary key default gen_random_uuid(), external_seed_key text unique, project_id uuid not null references public.projects(id), title text not null, occurred_at timestamptz not null, notes text, created_at timestamptz not null default now());
create table if not exists public.meeting_actions (id uuid primary key default gen_random_uuid(), meeting_id uuid not null references public.meetings(id) on delete cascade, entity_type text not null, entity_id uuid not null, created_at timestamptz not null default now());
create table if not exists public.readiness_checklists (id uuid primary key default gen_random_uuid(), workstream_id uuid not null unique references public.workstreams(id), target_filing_date date, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.readiness_items (id uuid primary key default gen_random_uuid(), checklist_id uuid not null references public.readiness_checklists(id) on delete cascade, name text not null, status text not null check(status in ('ready','underway','missing','waived')), assigned_organization_id uuid references public.organizations(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.escalation_policies (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null, thresholds jsonb not null, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.escalation_events (id uuid primary key default gen_random_uuid(), workstream_id uuid not null references public.workstreams(id), policy_id uuid references public.escalation_policies(id), level text not null check(level in ('warning','supervisor','liaison','state_office','executive')), status text not null default 'open', created_at timestamptz not null default now(), resolved_at timestamptz);

alter table public.audit_events add column if not exists entity_type text;
alter table public.audit_events add column if not exists entity_id uuid;
alter table public.audit_events add column if not exists reason text;
alter table public.audit_events add column if not exists source_channel text not null default 'web';
create table if not exists public.external_filings (id uuid primary key default gen_random_uuid(), workstream_id uuid not null references public.workstreams(id), permit_type_id uuid references public.permit_types(id), authority_name text not null, external_reference text, authoritative_url text not null, status text, verified_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create index if not exists workstreams_project_state_idx on public.workstreams(project_id,state);
create index if not exists tasks_workstream_status_idx on public.tasks(workstream_id,status);
create index if not exists task_dependencies_successor_idx on public.task_dependencies(successor_task_id);
create index if not exists coordination_target_status_due_idx on public.coordination_requests(target_organization_id,status,due_date);
create index if not exists rfis_workstream_status_idx on public.rfis(workstream_id,status);
create index if not exists document_versions_document_idx on public.document_versions(document_id,version_number desc);
create index if not exists audit_events_entity_idx on public.audit_events(entity_type,entity_id,created_at desc);

-- RLS helpers. Their private schema and explicit auth.uid checks prevent a
-- caller from manufacturing tenant access through client-controlled metadata.
create or replace function app_private.has_capability(p_org uuid, p_capability text) returns boolean language sql stable security definer set search_path = public, app_private as $$
 select exists(select 1 from public.organization_memberships m join public.membership_capabilities mc on mc.membership_id=m.id join public.capabilities c on c.id=mc.capability_id where m.user_id=(select auth.uid()) and m.organization_id=p_org and m.status='active' and c.code=p_capability);
$$;
create or replace function app_private.can_access_workstream(p_workstream uuid) returns boolean language sql stable security definer set search_path = public, app_private as $$
 select exists(select 1 from public.workstreams w where w.id=p_workstream and (app_private.is_org_member(w.lead_organization_id) or exists(select 1 from public.project_participants pp where pp.project_id=w.project_id and app_private.is_org_member(pp.organization_id))));
$$;
revoke all on function app_private.has_capability(uuid,text) from public, anon;
revoke all on function app_private.can_access_workstream(uuid) from public, anon;
grant execute on function app_private.has_capability(uuid,text), app_private.can_access_workstream(uuid) to authenticated;

-- Service-layer RPC: one transaction means an RFI acceptance cannot leave a
-- clock/audit/notification partially updated. No browser insert policy exists
-- for audit events.
create or replace function public.accept_rfi_response(p_rfi_id uuid, p_response_id uuid, p_reason text default null) returns void language plpgsql security invoker set search_path = public as $$
declare v_ws uuid; v_org uuid; begin
 select r.workstream_id,r.requesting_organization_id into v_ws,v_org from public.rfis r where r.id=p_rfi_id for update;
 if v_ws is null or not app_private.has_capability(v_org,'accept_rfi_response') then raise exception 'not authorized'; end if;
 update public.rfi_responses set status='accepted',reviewed_by=auth.uid(),reviewed_at=now() where id=p_response_id and rfi_id=p_rfi_id;
 if not found then raise exception 'response not found'; end if;
 update public.rfis set status='accepted',updated_at=now() where id=p_rfi_id;
 update public.workstreams set state='running',waiting_on_type=null,waiting_on_id=null,waiting_reason=null,updated_at=now() where id=v_ws;
 insert into public.audit_events(actor_id,organization_id,action,entity_type,entity_id,after_data,reason,source_channel) values(auth.uid(),v_org,'rfi_response_accepted','rfi',p_rfi_id,jsonb_build_object('status','accepted'),p_reason,'rpc');
end $$;

-- Every newly exposed operational table is RLS-protected. Direct writes are
-- intentionally absent; command RPCs/server services own state transitions.
do $$ declare t text; begin foreach t in array array['organizational_units','capabilities','membership_capabilities','permit_types','requirement_resources','permit_type_relations','workflow_templates','workflow_versions','workflow_stages','workflow_transitions','workflow_stage_requirements','workstreams','workflow_instances','tasks','task_dependencies','commitments','coordination_requests','rfis','rfi_items','rfi_responses','documents','document_versions','document_references','document_agency_reviews','decisions','meetings','meeting_actions','readiness_checklists','readiness_items','escalation_policies','escalation_events','external_filings'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create policy workstreams_read on public.workstreams for select to authenticated using ((select app_private.can_access_workstream(id)));
create policy tasks_read on public.tasks for select to authenticated using ((select app_private.can_access_workstream(workstream_id)));
create policy cr_read on public.coordination_requests for select to authenticated using ((select app_private.can_access_workstream(workstream_id)));
create policy rfi_read on public.rfis for select to authenticated using ((select app_private.can_access_workstream(workstream_id)));
create policy document_versions_read on public.document_versions for select to authenticated using (exists(select 1 from public.documents d join public.workstreams w on w.project_id=d.project_id where d.id=document_id and app_private.can_access_workstream(w.id)));
create policy documents_read on public.documents for select to authenticated using (exists(select 1 from public.workstreams w where w.project_id=documents.project_id and app_private.can_access_workstream(w.id)));

insert into storage.buckets(id,name,public) values ('path-documents','path-documents',false) on conflict(id) do update set public=false;
drop policy if exists path_documents_read_v2 on storage.objects;
create policy path_documents_read_v2 on storage.objects for select to authenticated using (bucket_id='path-documents' and exists(select 1 from public.document_versions dv where dv.storage_path=name and dv.scan_status='clean' and exists(select 1 from public.documents d join public.workstreams w on w.project_id=d.project_id where d.id=dv.document_id and app_private.can_access_workstream(w.id))));
